command: predict.py --checkpoint checkpoints/finetune_clean/youthful-wave-590_exp5_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_rcx_inhouse_beam10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/rcx_inhouse/rcx_inhouse_no_overlaps.jsonl
  data_split: all
  dataset_name: RCX_NO
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 05/01/2025 21:45:07
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 05/01/2025 22:08:44
generation_time: 00:23:34
wall_time_utc: 00:23:37
evaluation_0:
    average_num_of_predictions: '9.63963963963964'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:03
    formula_stats:
        num_all_correct_formulas: 28 / 1070
        num_at_least_one_correct_formula: '17'
        num_correct_formulas_at_best_prob: '4'
        num_correct_formulas_at_best_simil: '9'
        rate_of_all_correct_formulas: '0.026168224299065422'
        rate_of_at_least_one_correct_formula: '0.15315315315315314'
        rate_of_correct_formulas_at_best_prob: '0.036036036036036036'
        rate_of_correct_formulas_at_best_simil: '0.08108108108108109'
    hit_at_k_prob: '[(1, 0.02702702702702703), (2, 0.04504504504504504), (3, 0.05405405405405406),
        (4, 0.06306306306306306), (5, 0.07207207207207207), (7, 0.08108108108108109)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_no_overlaps.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '53.71800531145781'
        mean_absolute_mw_difference_best_simil: '52.27055462974772'
        mean_relative_mw_difference_best_prob: 15.76%
        mean_relative_mw_difference_best_simil: 15.49%
        rate_of_exact_mw_prob: '0.036036036036036036'
        rate_of_exact_mw_simil: '0.09009009009009009'
        rate_of_exact_nominal_mw_simil: '0.10810810810810811'
        rate_of_mw_difference_less_than_1_best_prob: '0.08108108108108109'
        rate_of_mw_difference_less_than_1_best_simil: '0.13513513513513514'
    num_datapoints_tested: '111'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[111, 111, 111, 111, 111, 111, 111, 109, 99, 85]'
    precise_preds_stats:
        num_precise_preds_probsort: '2'
        num_precise_preds_similsort: '8'
        rate_of_precise_preds_probsort: '0.018018018018018018'
        rate_of_precise_preds_similsort: '0.07207207207207207'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8), (2, 1)])
        num_1_hits_as_first_probsort: '3'
        num_1_hits_as_first_similsort: '9'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '1'
        rate_of_1_hits_as_first_probsort: '0.02702702702702703'
        rate_of_1_hits_as_first_similsort: '0.08108108108108109'
    start_time_utc: 07/01/2025 13:50:00
    threshold_stats:
        num_better_than_threshold_probsort: '4'
        num_better_than_threshold_similsort: '9'
        rate_of_better_than_threshold_probsort: '0.036036036036036036'
        rate_of_better_than_threshold_similsort: '0.08108108108108109'
        threshold: '0.85'
    topk_probsort: '[0.33629428640754644, 0.31145772227045854, 0.2866637295522499,
        0.280978746680247, 0.26422225719393844, 0.27176031150778757, 0.28043351134907785,
        0.2784004767470588, 0.2530871248274223, 0.2686518472591669]'
    topk_similsort: '[0.4399726492681182, 0.36617914919141903, 0.33143875975080217,
        0.3041426919753114, 0.27860675470981927, 0.257248588973373, 0.235005236858186,
        0.21619827720805196, 0.19546667222272504, 0.17944622440765512]'
