command: predict.py --checkpoint ../checkpoints/finetune_clean/youthful-wave-590_exp5_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_mona_oo_greedy.yaml
cuda_visible_devices: GPU-83f9775f-f502-4683-141b-c510e5f0c080
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_overlaps_only.jsonl
  data_split: all
  dataset_name: MONA_GCMS_overlaps_only
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/01/2025 02:09:57
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 07/01/2025 03:12:48
generation_time: 01:02:47
wall_time_utc: 01:02:51
evaluation_0:
    average_num_of_predictions: '0.9924753096096567'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:12
    formula_stats:
        num_all_correct_formulas: 8359 / 12662
        num_at_least_one_correct_formula: '8359'
        num_correct_formulas_at_best_prob: '8359'
        num_correct_formulas_at_best_simil: '8359'
        rate_of_all_correct_formulas: '0.660164271047228'
        rate_of_at_least_one_correct_formula: '0.6551967393008309'
        rate_of_correct_formulas_at_best_prob: '0.6551967393008309'
        rate_of_correct_formulas_at_best_simil: '0.6551967393008309'
    hit_at_k_prob: '[(1, 0.6057375764226368)]'
    labels_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_overlaps_only.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '42.71712286599922'
        mean_absolute_mw_difference_best_simil: '42.71712286599922'
        mean_relative_mw_difference_best_prob: 28.66%
        mean_relative_mw_difference_best_simil: 28.66%
        rate_of_exact_mw_prob: '0.6546480639598683'
        rate_of_exact_mw_simil: '0.6546480639598683'
        rate_of_exact_nominal_mw_prob: '0.6700893556983853'
        rate_of_exact_nominal_mw_simil: '0.6700893556983853'
        rate_of_mw_difference_less_than_1_best_prob: '0.6785546323875216'
        rate_of_mw_difference_less_than_1_best_simil: '0.6785546323875216'
    num_datapoints_tested: '12758'
    num_empty_preds: '96'
    num_predictions_at_k_counter: '[12758]'
    precise_preds_stats:
        num_precise_preds_probsort: '7673'
        num_precise_preds_similsort: '7673'
        rate_of_precise_preds_probsort: '0.6014265558865026'
        rate_of_precise_preds_similsort: '0.6014265558865026'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 7728)])
        num_1_hits_as_first_probsort: '7728'
        num_1_hits_as_first_similsort: '7728'
        num_fp_simil_fail_prob: '55'
        num_fp_simil_fail_simil: '55'
        rate_of_1_hits_as_first_probsort: '0.6057375764226368'
        rate_of_1_hits_as_first_similsort: '0.6057375764226368'
    start_time_utc: 07/01/2025 13:50:00
    threshold_stats:
        num_better_than_threshold_probsort: '7749'
        num_better_than_threshold_similsort: '7749'
        rate_of_better_than_threshold_probsort: '0.6073836024455244'
        rate_of_better_than_threshold_similsort: '0.6073836024455244'
        threshold: '0.85'
    topk_probsort: '[0.691330759456295]'
    topk_similsort: '[0.691330759456295]'
