command: predict.py --checkpoint checkpoints/finetune_clean/dulcet-cloud-568_exp3_custom_neims/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 31/10/2024 11:35:43
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 31/10/2024 18:50:13
generation_time: 07:14:27
wall_time_utc: 07:14:29
evaluation_0:
    average_num_of_predictions: '0.9853426553572062'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.23190393307662432'
        mean_fpsd_score_similsort: '0.23190393307662432'
        rate_of_spectus_wins_probsort: '0.7001809986868722'
        rate_of_spectus_wins_similsort: '0.7001809986868722'
        rate_of_ties_probsort: '0.14369876140114277'
        rate_of_ties_similsort: '0.14369876140114277'
        ties:
            mean_tie_simils_probsort: '0.7252662033964448'
            mean_tie_simils_similsort: '0.7252662033964448'
            num_of_ties_probsort: '4049'
            num_of_ties_simils_equal_to_1_probsort: '1705'
            num_of_ties_simils_equal_to_1_similsort: '1705'
            num_of_ties_similsort: '4049'
            rate_of_ties_simils_equal_to_1_probsort: '0.42109162756236107'
            rate_of_ties_simils_equal_to_1_similsort: '0.42109162756236107'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:32
    formula_stats:
        num_all_correct_formulas: 17639 / 27764
        num_at_least_one_correct_formula: '17639'
        num_correct_formulas_at_best_prob: '17639'
        num_correct_formulas_at_best_simil: '17639'
        rate_of_all_correct_formulas: '0.6353191182826682'
        rate_of_at_least_one_correct_formula: '0.6260070270078433'
        rate_of_correct_formulas_at_best_prob: '0.6260070270078433'
        rate_of_correct_formulas_at_best_simil: '0.6260070270078433'
    hit_at_k_prob: '[(1, 0.3818007594846861)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.294602848330555'
        mean_absolute_mw_difference_best_simil: '6.294602848330555'
        mean_relative_mw_difference_best_prob: 2.29%
        mean_relative_mw_difference_best_simil: 2.29%
        rate_of_exact_mw_prob: '0.6169570926642297'
        rate_of_exact_mw_simil: '0.6169570926642297'
        rate_of_exact_nominal_mw_simil: '0.6638747914966107'
        rate_of_mw_difference_less_than_1_best_prob: '0.69631259537921'
        rate_of_mw_difference_less_than_1_best_simil: '0.69631259537921'
    num_datapoints_tested: '28177'
    num_empty_preds: '413'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '10364'
        num_precise_preds_similsort: '10364'
        rate_of_precise_preds_probsort: '0.36781772367533805'
        rate_of_precise_preds_similsort: '0.36781772367533805'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 10758)])
        num_1_hits_as_first_probsort: '10758'
        num_1_hits_as_first_similsort: '10758'
        num_fp_simil_fail_prob: '394'
        num_fp_simil_fail_simil: '394'
        rate_of_1_hits_as_first_probsort: '0.3818007594846861'
        rate_of_1_hits_as_first_similsort: '0.3818007594846861'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '11054'
        num_better_than_threshold_similsort: '11054'
        rate_of_better_than_threshold_probsort: '0.39230578131099836'
        rate_of_better_than_threshold_similsort: '0.39230578131099836'
        threshold: '0.85'
    topk_probsort: '[0.6192197264181869]'
    topk_similsort: '[0.6192197264181869]'
