command: spectus/predict.py --checkpoint checkpoints/finetune_clean/balmy-violet-577_exp5_224_148/checkpoint-147476
  --output-folder predictions --config-file configs/predict_rcx_inhouse_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/rcx_inhouse/rcx_inhouse_no_overlaps.jsonl
  data_split: all
  dataset_name: RCX_NO
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 15/11/2024 14:54:07
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 15/11/2024 14:55:43
generation_time: 00:01:33
wall_time_utc: 00:01:36
evaluation_0:
    average_num_of_predictions: '1.0'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 3 / 111
        num_at_least_one_correct_formula: '3'
        num_correct_formulas_at_best_prob: '3'
        num_correct_formulas_at_best_simil: '3'
        rate_of_all_correct_formulas: '0.02702702702702703'
        rate_of_at_least_one_correct_formula: '0.02702702702702703'
        rate_of_correct_formulas_at_best_prob: '0.02702702702702703'
        rate_of_correct_formulas_at_best_simil: '0.02702702702702703'
    hit_at_k_prob: '[(1, 0.009009009009009009)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_no_overlaps.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '51.29231914369368'
        mean_absolute_mw_difference_best_simil: '51.29231914369368'
        mean_relative_mw_difference_best_prob: 15.43%
        mean_relative_mw_difference_best_simil: 15.43%
        rate_of_exact_mw_prob: '0.02702702702702703'
        rate_of_exact_mw_simil: '0.02702702702702703'
        rate_of_exact_nominal_mw_simil: '0.02702702702702703'
        rate_of_mw_difference_less_than_1_best_prob: '0.02702702702702703'
        rate_of_mw_difference_less_than_1_best_simil: '0.02702702702702703'
    num_datapoints_tested: '111'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[111]'
    precise_preds_stats:
        num_precise_preds_probsort: '1'
        num_precise_preds_similsort: '1'
        rate_of_precise_preds_probsort: '0.009009009009009009'
        rate_of_precise_preds_similsort: '0.009009009009009009'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 1)])
        num_1_hits_as_first_probsort: '1'
        num_1_hits_as_first_similsort: '1'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.009009009009009009'
        rate_of_1_hits_as_first_similsort: '0.009009009009009009'
    start_time_utc: 15/11/2024 15:49:46
    threshold_stats:
        num_better_than_threshold_probsort: '2'
        num_better_than_threshold_similsort: '2'
        rate_of_better_than_threshold_probsort: '0.018018018018018018'
        rate_of_better_than_threshold_similsort: '0.018018018018018018'
        threshold: '0.85'
    topk_probsort: '[0.30846640340187387]'
    topk_similsort: '[0.30846640340187387]'
evaluation_1:
    average_num_of_predictions: '1.0'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 3 / 111
        num_at_least_one_correct_formula: '3'
        num_correct_formulas_at_best_prob: '3'
        num_correct_formulas_at_best_simil: '3'
        rate_of_all_correct_formulas: '0.02702702702702703'
        rate_of_at_least_one_correct_formula: '0.02702702702702703'
        rate_of_correct_formulas_at_best_prob: '0.02702702702702703'
        rate_of_correct_formulas_at_best_simil: '0.02702702702702703'
    hit_at_k_prob: '[(1, 0.009009009009009009)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_no_overlaps.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '51.29231914369368'
        mean_absolute_mw_difference_best_simil: '51.29231914369368'
        mean_relative_mw_difference_best_prob: 15.43%
        mean_relative_mw_difference_best_simil: 15.43%
        rate_of_exact_mw_prob: '0.02702702702702703'
        rate_of_exact_mw_simil: '0.02702702702702703'
        rate_of_exact_nominal_mw_simil: '0.02702702702702703'
        rate_of_mw_difference_less_than_1_best_prob: '0.02702702702702703'
        rate_of_mw_difference_less_than_1_best_simil: '0.02702702702702703'
    num_datapoints_tested: '111'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[111]'
    precise_preds_stats:
        num_precise_preds_probsort: '1'
        num_precise_preds_similsort: '1'
        rate_of_precise_preds_probsort: '0.009009009009009009'
        rate_of_precise_preds_similsort: '0.009009009009009009'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 1)])
        num_1_hits_as_first_probsort: '1'
        num_1_hits_as_first_similsort: '1'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.009009009009009009'
        rate_of_1_hits_as_first_similsort: '0.009009009009009009'
    start_time_utc: 20/11/2024 21:36:54
    threshold_stats:
        num_better_than_threshold_probsort: '2'
        num_better_than_threshold_similsort: '2'
        rate_of_better_than_threshold_probsort: '0.018018018018018018'
        rate_of_better_than_threshold_similsort: '0.018018018018018018'
        threshold: '0.85'
    topk_probsort: '[0.30846640340187387]'
    topk_similsort: '[0.30846640340187387]'
evaluation_2:
    average_num_of_predictions: '1.0'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 3 / 111
        num_at_least_one_correct_formula: '3'
        num_correct_formulas_at_best_prob: '3'
        num_correct_formulas_at_best_simil: '3'
        rate_of_all_correct_formulas: '0.02702702702702703'
        rate_of_at_least_one_correct_formula: '0.02702702702702703'
        rate_of_correct_formulas_at_best_prob: '0.02702702702702703'
        rate_of_correct_formulas_at_best_simil: '0.02702702702702703'
    hit_at_k_prob: '[(1, 0.009009009009009009)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_no_overlaps.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '51.29231914369368'
        mean_absolute_mw_difference_best_simil: '51.29231914369368'
        mean_relative_mw_difference_best_prob: 15.43%
        mean_relative_mw_difference_best_simil: 15.43%
        rate_of_exact_mw_prob: '0.02702702702702703'
        rate_of_exact_mw_simil: '0.02702702702702703'
        rate_of_exact_nominal_mw_simil: '0.02702702702702703'
        rate_of_mw_difference_less_than_1_best_prob: '0.02702702702702703'
        rate_of_mw_difference_less_than_1_best_simil: '0.02702702702702703'
    num_datapoints_tested: '111'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[111]'
    precise_preds_stats:
        num_precise_preds_probsort: '1'
        num_precise_preds_similsort: '1'
        rate_of_precise_preds_probsort: '0.009009009009009009'
        rate_of_precise_preds_similsort: '0.009009009009009009'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 1)])
        num_1_hits_as_first_probsort: '1'
        num_1_hits_as_first_similsort: '1'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.009009009009009009'
        rate_of_1_hits_as_first_similsort: '0.009009009009009009'
    start_time_utc: 20/11/2024 21:44:21
    threshold_stats:
        num_better_than_threshold_probsort: '2'
        num_better_than_threshold_similsort: '2'
        rate_of_better_than_threshold_probsort: '0.018018018018018018'
        rate_of_better_than_threshold_similsort: '0.018018018018018018'
        threshold: '0.85'
    topk_probsort: '[0.30846640340187387]'
    topk_similsort: '[0.30846640340187387]'
