command: predict.py --checkpoint checkpoints/finetune_clean/vibrant-armadillo-584_exp5_224_74/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/01/2025 21:45:52
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 08/01/2025 08:08:54
generation_time: '10:22:59'
wall_time_utc: '10:23:02'
evaluation_0:
    average_num_of_predictions: '8.496930120310893'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:01
    formula_stats:
        num_all_correct_formulas: 74702 / 239418
        num_at_least_one_correct_formula: '23576'
        num_correct_formulas_at_best_prob: '18145'
        num_correct_formulas_at_best_simil: '20784'
        rate_of_all_correct_formulas: '0.3120149696346975'
        rate_of_at_least_one_correct_formula: '0.836710792490329'
        rate_of_correct_formulas_at_best_prob: '0.6439649359406608'
        rate_of_correct_formulas_at_best_simil: '0.7376228839124108'
    hit_at_k_prob: '[(1, 0.38552720303793875), (2, 0.48262767505412213), (3, 0.5319586897114668),
        (4, 0.5634382652518011), (5, 0.584483798843028), (6, 0.5990346736700145),
        (7, 0.6084749973382546), (8, 0.6160698441991695), (9, 0.620044717322639),
        (10, 0.6212868651737232)]'
    labels_path: data/nist/valid.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.100106863871861'
        mean_absolute_mw_difference_best_simil: '6.5675228732526545'
        mean_relative_mw_difference_best_prob: 2.18%
        mean_relative_mw_difference_best_simil: 2.29%
        rate_of_exact_mw_prob: '0.6337438336231679'
        rate_of_exact_mw_simil: '0.6638038116194059'
        rate_of_exact_nominal_mw_prob: '0.6816552507364162'
        rate_of_exact_nominal_mw_simil: '0.6911665542818611'
        rate_of_mw_difference_less_than_1_best_prob: '0.7122830677502928'
        rate_of_mw_difference_less_than_1_best_simil: '0.7129573765837385'
    num_datapoints_tested: '28177'
    num_empty_preds: '2'
    num_predictions_at_k_counter: '[28177, 28087, 27874, 27512, 26837, 25735, 24101,
        21533, 17794, 11770]'
    precise_preds_stats:
        num_precise_preds_probsort: '10396'
        num_precise_preds_similsort: '17419'
        rate_of_precise_preds_probsort: '0.368953401710615'
        rate_of_precise_preds_similsort: '0.6181992405153139'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 14557), (2, 1387), (6, 73), (4, 329),
            (3, 974), (5, 130), (8, 14), (7, 31), (10, 6), (9, 5)])
        num_1_hits_as_first_probsort: '10863'
        num_1_hits_as_first_similsort: '17506'
        num_fp_simil_fail_prob: '467'
        num_fp_simil_fail_simil: '87'
        rate_of_1_hits_as_first_probsort: '0.38552720303793875'
        rate_of_1_hits_as_first_similsort: '0.6212868651737232'
    start_time_utc: 08/01/2025 09:39:33
    threshold_stats:
        num_better_than_threshold_probsort: '11191'
        num_better_than_threshold_similsort: '17695'
        rate_of_better_than_threshold_probsort: '0.39716790289952797'
        rate_of_better_than_threshold_similsort: '0.627994463569578'
        threshold: '0.85'
    topk_probsort: '[0.6356418717881716, 0.5257375206355113, 0.4823608820972434, 0.4573265606069522,
        0.4388089334222519, 0.4210184583132382, 0.40456278897436776, 0.3847530406591405,
        0.3653037688160345, 0.34026960862343486]'
    topk_similsort: '[0.787161791757166, 0.5927083041846165, 0.515325658224393, 0.46144814923548255,
        0.4183835574327659, 0.38128789310468414, 0.34639680122440525, 0.3122463184686504,
        0.2786098034420513, 0.24628163513150034]'
