command: predict.py --checkpoint checkpoints/finetune_clean/youthful-wave-590_exp5_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_cayman_beam10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/Cayman_library/Cayman_library_noD.jsonl
  data_split: all
  dataset_name: Cayman_library
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 05/01/2025 21:45:07
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 05/01/2025 22:44:26
generation_time: 00:59:16
wall_time_utc: 00:59:18
evaluation_0:
    average_num_of_predictions: '8.991471215351812'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:05
    formula_stats:
        num_all_correct_formulas: 757 / 4217
        num_at_least_one_correct_formula: '285'
        num_correct_formulas_at_best_prob: '199'
        num_correct_formulas_at_best_simil: '234'
        rate_of_all_correct_formulas: '0.1795115010671093'
        rate_of_at_least_one_correct_formula: '0.6076759061833689'
        rate_of_correct_formulas_at_best_prob: '0.42430703624733473'
        rate_of_correct_formulas_at_best_simil: '0.4989339019189765'
    hit_at_k_prob: '[(1, 0.208955223880597), (2, 0.302771855010661), (3, 0.3304904051172708),
        (4, 0.34968017057569295), (5, 0.3624733475479744), (6, 0.3795309168443497),
        (7, 0.3837953091684435), (8, 0.3880597014925373), (9, 0.39232409381663114),
        (10, 0.39658848614072495)]'
    labels_path: data/extra_libraries/Cayman_library/Cayman_library_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '31.65120140539872'
        mean_absolute_mw_difference_best_simil: '31.047152053381474'
        mean_relative_mw_difference_best_prob: 11.05%
        mean_relative_mw_difference_best_simil: 10.89%
        rate_of_exact_mw_prob: '0.39872068230277186'
        rate_of_exact_mw_simil: '0.47547974413646055'
        rate_of_exact_nominal_mw_simil: '0.4968017057569296'
        rate_of_mw_difference_less_than_1_best_prob: '0.4520255863539446'
        rate_of_mw_difference_less_than_1_best_simil: '0.509594882729211'
    num_datapoints_tested: '469'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[469, 467, 467, 464, 462, 453, 432, 407, 350, 246]'
    precise_preds_stats:
        num_precise_preds_probsort: '96'
        num_precise_preds_similsort: '182'
        rate_of_precise_preds_probsort: '0.2046908315565032'
        rate_of_precise_preds_similsort: '0.3880597014925373'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 176), (4, 1), (2, 7), (3, 2)])
        num_1_hits_as_first_probsort: '98'
        num_1_hits_as_first_similsort: '186'
        num_fp_simil_fail_prob: '2'
        num_fp_simil_fail_simil: '4'
        rate_of_1_hits_as_first_probsort: '0.208955223880597'
        rate_of_1_hits_as_first_similsort: '0.39658848614072495'
    start_time_utc: 07/01/2025 13:50:00
    threshold_stats:
        num_better_than_threshold_probsort: '114'
        num_better_than_threshold_similsort: '199'
        rate_of_better_than_threshold_probsort: '0.24307036247334754'
        rate_of_better_than_threshold_similsort: '0.42430703624733473'
        threshold: '0.85'
    topk_probsort: '[0.6171989654331868, 0.5488883283730276, 0.4955539247680706, 0.481807311495045,
        0.4730403779200813, 0.4703777399188658, 0.4453608428898913, 0.4277416444361889,
        0.409956257245446, 0.39742056415073296]'
    topk_similsort: '[0.7367439370455939, 0.6019681366230427, 0.5412502029304667,
        0.49916810586750204, 0.4616899927386016, 0.4311546697695279, 0.40275450029200266,
        0.36806157993797534, 0.33799099409736083, 0.31874196438142094]'
