name: rassp_cpu
channels:
  - pytorch
  - nvidia
  - https://conda.anaconda.org/rdkit
  - conda-forge # RL/numpy/scipy
  # - dglteam # DGL
dependencies:
  - python=3.7.9

  - pandas=1.1.3
  - matplotlib=3.3.3

  - pytorch=1.13
  # - pytorch-cuda=11.6
  # - torchvision=0.1
  # - cudatoolkit=11.3

  # - conda-forge::rdkit
  - rdkit=2020.09.1.0

  - cython=0.29.23
  - numba=0.52.0
  - pytest=6.2.2
  - scikit-learn=0.23.2

  - pip=20.3.1
  - pip:
    - scipy==1.5.4
    - numpy==1.21.6  # 1.19 doesn't work with tinygraph
    - python-igraph==0.8.3
    - ruffus==2.8.4
    - tqdm==4.54.1
    - boto3==1.16.33
    - networkx==2.5
    - graphviz==0.15
    - tensorflow-gpu==2.5.0
    - tensorboardX==2.1
    - git+https://github.com/thejonaslab/tinygraph.git
    - diskcache==5.2.1
    - PyYAML==5.3.1
    - natsort==7.1.0
    - pyarrow==2.0.0
    - seaborn==0.11.1
    - SQLAlchemy==1.4.46
    - click==8.0.3
