command: src/predict.py --checkpoint ../checkpoints/finetune_clean/balmy-violet-577_exp5_224_148/checkpoint-147476
  --output-folder predictions --config-file configs/predict_cayman_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/Cayman_library/Cayman_library_noD.jsonl
  data_split: all
  dataset_name: Cayman_library
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/11/2024 12:33:05
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 06/11/2024 13:03:59
generation_time: 00:30:50
wall_time_utc: 00:30:53
evaluation_0:
    average_num_of_predictions: '9.251599147121535'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:07
    formula_stats:
        num_all_correct_formulas: 782 / 4339
        num_at_least_one_correct_formula: '275'
        num_correct_formulas_at_best_prob: '178'
        num_correct_formulas_at_best_simil: '223'
        rate_of_all_correct_formulas: '0.18022585849274025'
        rate_of_at_least_one_correct_formula: '0.5863539445628998'
        rate_of_correct_formulas_at_best_prob: '0.3795309168443497'
        rate_of_correct_formulas_at_best_simil: '0.47547974413646055'
    hit_at_k_prob: '[(1, 0.17484008528784648), (2, 0.232409381663113), (3, 0.26652452025586354),
        (4, 0.31556503198294245), (5, 0.3347547974413646), (6, 0.3582089552238806),
        (7, 0.3624733475479744), (8, 0.36886993603411516)]'
    labels_path: data/extra_libraries/Cayman_library/Cayman_library_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '32.87328590548847'
        mean_absolute_mw_difference_best_simil: '33.86336306394457'
        mean_relative_mw_difference_best_prob: 11.60%
        mean_relative_mw_difference_best_simil: 11.90%
        rate_of_exact_mw_prob: '0.36886993603411516'
        rate_of_exact_mw_simil: '0.4349680170575693'
        rate_of_exact_nominal_mw_prob: '0.40298507462686567'
        rate_of_exact_nominal_mw_simil: '0.4541577825159915'
        rate_of_mw_difference_less_than_1_best_prob: '0.42643923240938164'
        rate_of_mw_difference_less_than_1_best_simil: '0.47334754797441364'
    num_datapoints_tested: '469'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[469, 469, 469, 468, 465, 460, 448, 424, 384, 283]'
    precise_preds_stats:
        num_precise_preds_probsort: '81'
        num_precise_preds_similsort: '171'
        rate_of_precise_preds_probsort: '0.17270788912579957'
        rate_of_precise_preds_similsort: '0.3646055437100213'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 165), (2, 6), (4, 1), (3, 1)])
        num_1_hits_as_first_probsort: '82'
        num_1_hits_as_first_similsort: '173'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '2'
        rate_of_1_hits_as_first_probsort: '0.17484008528784648'
        rate_of_1_hits_as_first_similsort: '0.36886993603411516'
    start_time_utc: 06/11/2024 17:51:47
    threshold_stats:
        num_better_than_threshold_probsort: '92'
        num_better_than_threshold_similsort: '190'
        rate_of_better_than_threshold_probsort: '0.19616204690831557'
        rate_of_better_than_threshold_similsort: '0.4051172707889126'
        threshold: '0.85'
    topk_probsort: '[0.581741362301865, 0.5235702974403511, 0.4925392486118762, 0.4901731120103012,
        0.47100578012453587, 0.4507730741833013, 0.43569875552793463, 0.4353748991789571,
        0.416473361457001, 0.3909675024490123]'
    topk_similsort: '[0.7180697947280209, 0.5975846317014523, 0.5367930295035582,
        0.4944526866906819, 0.45571781452136145, 0.4260750200038165, 0.39801819525389054,
        0.36993312342654716, 0.3320072067574616, 0.2995349741434124]'
