command: spectus/predict.py --checkpoint checkpoints/finetune_clean/balmy-violet-577_exp5_224_148/checkpoint-147476
  --output-folder predictions --config-file configs/predict_mona_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_overlaps_included.jsonl
  data_split: all
  dataset_name: MONA_GCMS_overlaps_included
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/11/2024 16:32:43
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 06/11/2024 19:06:59
generation_time: 02:33:59
wall_time_utc: 02:34:15
evaluation_0:
    average_num_of_predictions: '0.9883224792274871'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:12
    formula_stats:
        num_all_correct_formulas: 10061 / 17604
        num_at_least_one_correct_formula: '10061'
        num_correct_formulas_at_best_prob: '10061'
        num_correct_formulas_at_best_simil: '10061'
        rate_of_all_correct_formulas: '0.5715178368552601'
        rate_of_at_least_one_correct_formula: '0.5648439254435212'
        rate_of_correct_formulas_at_best_prob: '0.5648439254435212'
        rate_of_correct_formulas_at_best_simil: '0.5648439254435212'
    hit_at_k_prob: '[(1, 0.4825398607680216)]'
    labels_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_overlaps_included.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '46.08913019387752'
        mean_absolute_mw_difference_best_simil: '46.08913019387752'
        mean_relative_mw_difference_best_prob: 29.76%
        mean_relative_mw_difference_best_simil: 29.76%
        rate_of_exact_mw_prob: '0.563496519200539'
        rate_of_exact_mw_simil: '0.563496519200539'
        rate_of_exact_nominal_mw_simil: '0.5870761284527285'
        rate_of_mw_difference_less_than_1_best_prob: '0.5995396362003144'
        rate_of_mw_difference_less_than_1_best_simil: '0.5995396362003144'
    num_datapoints_tested: '17812'
    num_empty_preds: '208'
    num_predictions_at_k_counter: '[17812]'
    precise_preds_stats:
        num_precise_preds_probsort: '8512'
        num_precise_preds_similsort: '8512'
        rate_of_precise_preds_probsort: '0.47788008084437456'
        rate_of_precise_preds_similsort: '0.47788008084437456'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8595)])
        num_1_hits_as_first_probsort: '8595'
        num_1_hits_as_first_similsort: '8595'
        num_fp_simil_fail_prob: '83'
        num_fp_simil_fail_simil: '83'
        rate_of_1_hits_as_first_probsort: '0.4825398607680216'
        rate_of_1_hits_as_first_similsort: '0.4825398607680216'
    start_time_utc: 07/11/2024 18:56:47
    threshold_stats:
        num_better_than_threshold_probsort: '8637'
        num_better_than_threshold_similsort: '8637'
        rate_of_better_than_threshold_probsort: '0.4848978216932405'
        rate_of_better_than_threshold_similsort: '0.4848978216932405'
        threshold: '0.85'
    topk_probsort: '[0.6004811620295712]'
    topk_similsort: '[0.6004811620295712]'
