command: predict.py --checkpoint ../checkpoints/finetune_clean/youthful-wave-590_exp5_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_mona_beam10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
  data_split: all
  dataset_name: MONA_GCMS
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 05/01/2025 21:45:07
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 06/01/2025 01:04:30
generation_time: 03:19:19
wall_time_utc: 03:19:22
evaluation_0:
    average_num_of_predictions: '8.949950149551347'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:14
    formula_stats:
        num_all_correct_formulas: 7503 / 44884
        num_at_least_one_correct_formula: '2633'
        num_correct_formulas_at_best_prob: '1936'
        num_correct_formulas_at_best_simil: '2225'
        rate_of_all_correct_formulas: '0.16716424561090812'
        rate_of_at_least_one_correct_formula: '0.525024925224327'
        rate_of_correct_formulas_at_best_prob: '0.3860418743768694'
        rate_of_correct_formulas_at_best_simil: '0.4436689930209372'
    hit_at_k_prob: '[(1, 0.21136590229312063), (2, 0.272382851445663), (3, 0.3036889332003988),
        (4, 0.3190428713858425), (5, 0.3288135593220339), (6, 0.3369890329012961),
        (7, 0.34137587238285144), (8, 0.34436689930209374), (9, 0.34576271186440677),
        (10, 0.3465603190428714)]'
    labels_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '58.791136585203056'
        mean_absolute_mw_difference_best_simil: '61.034435995942'
        mean_relative_mw_difference_best_prob: 34.58%
        mean_relative_mw_difference_best_simil: 35.43%
        rate_of_exact_mw_prob: '0.3826520438683948'
        rate_of_exact_mw_simil: '0.4201395812562313'
        rate_of_exact_nominal_mw_prob: '0.4279162512462612'
        rate_of_exact_nominal_mw_simil: '0.44666001994017945'
        rate_of_mw_difference_less_than_1_best_prob: '0.4442671984047856'
        rate_of_mw_difference_less_than_1_best_simil: '0.4642073778664008'
    num_datapoints_tested: '5015'
    num_empty_preds: '2'
    num_predictions_at_k_counter: '[5015, 4993, 4965, 4916, 4848, 4735, 4554, 4232,
        3775, 2853]'
    precise_preds_stats:
        num_precise_preds_probsort: '1014'
        num_precise_preds_similsort: '1707'
        rate_of_precise_preds_probsort: '0.20219341974077767'
        rate_of_precise_preds_similsort: '0.3403788634097707'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 1576), (2, 102), (3, 50), (4, 9), (5,
            1)])
        num_1_hits_as_first_probsort: '1060'
        num_1_hits_as_first_similsort: '1738'
        num_fp_simil_fail_prob: '46'
        num_fp_simil_fail_simil: '31'
        rate_of_1_hits_as_first_probsort: '0.21136590229312063'
        rate_of_1_hits_as_first_similsort: '0.3465603190428714'
    start_time_utc: 07/01/2025 13:49:59
    threshold_stats:
        num_better_than_threshold_probsort: '1084'
        num_better_than_threshold_similsort: '1758'
        rate_of_better_than_threshold_probsort: '0.21615154536390827'
        rate_of_better_than_threshold_similsort: '0.35054835493519443'
        threshold: '0.85'
    topk_probsort: '[0.40878317037562506, 0.3296005693275794, 0.30484599357624514,
        0.2813463320092835, 0.2710592538933915, 0.2592802561919882, 0.24847195840382258,
        0.23535499782125582, 0.22428136991082245, 0.20346046980004812]'
    topk_similsort: '[0.536109062966231, 0.3765167302972534, 0.3220397367755477, 0.28599522303450037,
        0.25838243679580813, 0.2340182420195491, 0.2097371093544611, 0.18576977615244014,
        0.1634846747959969, 0.1389006747770182]'
