command: predict.py --checkpoint checkpoints/finetune_clean/youthful-wave-590_exp5_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_nist_valid_beam10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/01/2025 10:52:35
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 07/01/2025 00:52:45
generation_time: '13:59:36'
wall_time_utc: '14:00:09'
evaluation_0:
    average_num_of_predictions: '8.081875288355752'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:03
    formula_stats:
        num_all_correct_formulas: 71812 / 227723
        num_at_least_one_correct_formula: '24183'
        num_correct_formulas_at_best_prob: '19100'
        num_correct_formulas_at_best_simil: '21699'
        rate_of_all_correct_formulas: '0.3153480324780545'
        rate_of_at_least_one_correct_formula: '0.8582531852219896'
        rate_of_correct_formulas_at_best_prob: '0.6778578273059588'
        rate_of_correct_formulas_at_best_simil: '0.7700961777336125'
    hit_at_k_prob: '[(1, 0.4229690882634773), (2, 0.5234765943854918), (3, 0.5730205486744508),
        (4, 0.6007027007843276), (5, 0.6207545160946871), (6, 0.6337083436845654),
        (7, 0.6427227880895766), (8, 0.6480107889413351), (9, 0.6515597828015758),
        (10, 0.6523405614508286)]'
    labels_path: data/nist/valid.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '5.756611067081987'
        mean_absolute_mw_difference_best_simil: '6.26455680188469'
        mean_relative_mw_difference_best_prob: 2.05%
        mean_relative_mw_difference_best_simil: 2.20%
        rate_of_exact_mw_prob: '0.6676367249884658'
        rate_of_exact_mw_simil: '0.6925506618873549'
        rate_of_exact_nominal_mw_simil: '0.7159385314263407'
        rate_of_mw_difference_less_than_1_best_prob: '0.73318664158711'
        rate_of_mw_difference_less_than_1_best_simil: '0.7317670440430138'
    num_datapoints_tested: '28177'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[28177, 28070, 27785, 27145, 26105, 24441, 22095,
        19157, 15161, 9587]'
    precise_preds_stats:
        num_precise_preds_probsort: '11474'
        num_precise_preds_similsort: '18266'
        rate_of_precise_preds_probsort: '0.40721155552400895'
        rate_of_precise_preds_similsort: '0.648259218511552'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 15572), (2, 1319), (6, 38), (4, 264),
            (3, 1077), (5, 86), (8, 8), (10, 3), (7, 11), (9, 3)])
        num_1_hits_as_first_probsort: '11918'
        num_1_hits_as_first_similsort: '18381'
        num_fp_simil_fail_prob: '444'
        num_fp_simil_fail_simil: '115'
        rate_of_1_hits_as_first_probsort: '0.4229690882634773'
        rate_of_1_hits_as_first_similsort: '0.6523405614508286'
    start_time_utc: 07/01/2025 13:50:00
    threshold_stats:
        num_better_than_threshold_probsort: '12251'
        num_better_than_threshold_similsort: '18589'
        rate_of_better_than_threshold_probsort: '0.4347872378180786'
        rate_of_better_than_threshold_similsort: '0.6597224686801292'
        threshold: '0.85'
    topk_probsort: '[0.6645633248131197, 0.5373970610359792, 0.49103919808076185,
        0.4578282983003017, 0.43621218837936027, 0.41626792378066707, 0.39625445311264035,
        0.3748833741049214, 0.35051054646519536, 0.32319160008343023]'
    topk_similsort: '[0.8081962475104617, 0.5936909198136355, 0.5145689707625051,
        0.4579407292276887, 0.41454304501925865, 0.3760841622518889, 0.3386317073552182,
        0.30340114549505126, 0.2689098860024158, 0.23383845384248647]'
