command: predict.py --checkpoint ../checkpoints/finetune_clean/devout-disco-532_exp2_log_20_1.43/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10_exp2_log_20_1.43.yaml
cuda_visible_devices: '0'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.43
  log_shift: 20
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/10/2024 00:15:13
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 09/10/2024 04:05:42
generation_time: 03:50:23
wall_time_utc: 03:50:29
evaluation_0:
    average_num_of_predictions: '8.783404904709515'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.17836662639755516'
        mean_fpsd_score_similsort: '0.3283278648861064'
        rate_of_spectus_wins_probsort: '0.6647975299002733'
        rate_of_spectus_wins_similsort: '0.8387337189906662'
        rate_of_ties_probsort: '0.09000248429570216'
        rate_of_ties_similsort: '0.09000248429570216'
        ties:
            mean_tie_simils_probsort: '0.8299671202203067'
            mean_tie_simils_similsort: '0.8711274486381235'
            num_of_ties_probsort: '2536'
            num_of_ties_simils_equal_to_1_probsort: '1651'
            num_of_ties_simils_equal_to_1_similsort: '1778'
            num_of_ties_similsort: '2536'
            rate_of_ties_simils_equal_to_1_probsort: '0.6510252365930599'
            rate_of_ties_simils_equal_to_1_similsort: '0.7011041009463722'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:15
    formula_stats:
        num_all_correct_formulas: 51352 / 247490
        num_at_least_one_correct_formula: '19829'
        num_correct_formulas_at_best_prob: '13643'
        num_correct_formulas_at_best_simil: '16809'
        rate_of_all_correct_formulas: '0.20749121176613197'
        rate_of_at_least_one_correct_formula: '0.7037299925471129'
        rate_of_correct_formulas_at_best_prob: '0.484189232352628'
        rate_of_correct_formulas_at_best_simil: '0.5965503779678462'
    hit_at_k_prob: '[(1, 0.29406963125953794), (2, 0.3763353089399155), (3, 0.42030734286829685),
        (4, 0.44834439436419776), (5, 0.46722504170067786), (6, 0.48216630585229087),
        (7, 0.49171309933633817), (8, 0.4975689392057352), (9, 0.5009404833729638),
        (10, 0.5023245909784576)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '10.066498727181'
        mean_absolute_mw_difference_best_simil: '10.443025518137327'
        mean_relative_mw_difference_best_prob: 3.82%
        mean_relative_mw_difference_best_simil: 3.90%
        rate_of_exact_mw_prob: '0.4773396742023636'
        rate_of_exact_mw_simil: '0.5191113319373958'
        rate_of_exact_nominal_mw_prob: '0.5032473293821201'
        rate_of_exact_nominal_mw_simil: '0.535117294247081'
        rate_of_mw_difference_less_than_1_best_prob: '0.5277708769563829'
        rate_of_mw_difference_less_than_1_best_simil: '0.5551691095574405'
    num_datapoints_tested: '28177'
    num_empty_preds: '6'
    num_predictions_at_k_counter: '[28177, 28145, 28050, 27853, 27401, 26631, 25310,
        23125, 19482, 13322]'
    precise_preds_stats:
        num_precise_preds_probsort: '7577'
        num_precise_preds_similsort: '13974'
        rate_of_precise_preds_probsort: '0.2689072647904319'
        rate_of_precise_preds_similsort: '0.4959364020300245'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 11225), (9, 14), (2, 1183), (4, 440),
            (3, 874), (6, 93), (5, 200), (8, 39), (7, 69), (10, 17)])
        num_1_hits_as_first_probsort: '8286'
        num_1_hits_as_first_similsort: '14154'
        num_fp_simil_fail_prob: '709'
        num_fp_simil_fail_simil: '180'
        rate_of_1_hits_as_first_probsort: '0.29406963125953794'
        rate_of_1_hits_as_first_similsort: '0.5023245909784576'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '8677'
        num_better_than_threshold_similsort: '14429'
        rate_of_better_than_threshold_probsort: '0.30794619725307876'
        rate_of_better_than_threshold_similsort: '0.5120843240941193'
        threshold: '0.85'
    topk_probsort: '[0.5656824197391178, 0.49387052154935907, 0.46091237352538134,
        0.43968296174447397, 0.4262589467358323, 0.4146246012081738, 0.40047124828051683,
        0.38595903595109826, 0.3632597135888978, 0.34097617865590374]'
    topk_similsort: '[0.715643658227669, 0.563156829637373, 0.49759690386534394, 0.45059352084583015,
        0.4119800490002874, 0.37817110011611554, 0.34499478570580494, 0.3119288396659686,
        0.2761935284405212, 0.2408347887474394]'
