command: predict.py --checkpoint ../checkpoints/finetune_clean/balmy-violet-577_exp8_224_148/checkpoint-147476
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 04/11/2024 12:35:58
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 04/11/2024 17:58:56
generation_time: 05:22:54
wall_time_utc: 05:22:57
evaluation_0:
    average_num_of_predictions: '0.9876140114277602'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.25587159313000124'
        mean_fpsd_score_similsort: '0.25587159313000124'
        rate_of_BART_wins_probsort: '0.7182098874968946'
        rate_of_BART_wins_similsort: '0.7182098874968946'
        rate_of_ties_probsort: '0.14345033183092593'
        rate_of_ties_similsort: '0.14345033183092593'
        ties:
            mean_tie_simils_probsort: '0.7253960603763996'
            mean_tie_simils_similsort: '0.7253960603763996'
            num_of_ties_probsort: '4042'
            num_of_ties_simils_equal_to_1_probsort: '1711'
            num_of_ties_simils_equal_to_1_similsort: '1711'
            num_of_ties_similsort: '4042'
            rate_of_ties_simils_equal_to_1_probsort: '0.42330529440870857'
            rate_of_ties_simils_equal_to_1_similsort: '0.42330529440870857'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 18223 / 27828
        num_at_least_one_correct_formula: '18223'
        num_correct_formulas_at_best_prob: '18223'
        num_correct_formulas_at_best_simil: '18223'
        rate_of_all_correct_formulas: '0.6548440419721144'
        rate_of_at_least_one_correct_formula: '0.6467331511516485'
        rate_of_correct_formulas_at_best_prob: '0.6467331511516485'
        rate_of_correct_formulas_at_best_simil: '0.6467331511516485'
    hit_at_k_prob: '[(1, 0.41225112680555065)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.164771192157531'
        mean_absolute_mw_difference_best_simil: '6.164771192157531'
        mean_relative_mw_difference_best_prob: 2.23%
        mean_relative_mw_difference_best_simil: 2.23%
        rate_of_exact_mw_prob: '0.6384285055186855'
        rate_of_exact_mw_simil: '0.6384285055186855'
        rate_of_exact_nominal_mw_prob: '0.6799872236221032'
        rate_of_exact_nominal_mw_simil: '0.6799872236221032'
        rate_of_mw_difference_less_than_1_best_prob: '0.7065336976967029'
        rate_of_mw_difference_less_than_1_best_simil: '0.7065336976967029'
    num_datapoints_tested: '28177'
    num_empty_preds: '349'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '11219'
        num_precise_preds_similsort: '11219'
        rate_of_precise_preds_probsort: '0.39816162118039533'
        rate_of_precise_preds_similsort: '0.39816162118039533'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 11616)])
        num_1_hits_as_first_probsort: '11616'
        num_1_hits_as_first_similsort: '11616'
        num_fp_simil_fail_prob: '397'
        num_fp_simil_fail_simil: '397'
        rate_of_1_hits_as_first_probsort: '0.41225112680555065'
        rate_of_1_hits_as_first_similsort: '0.41225112680555065'
    start_time_utc: 04/11/2024 22:14:56
    threshold_stats:
        num_better_than_threshold_probsort: '11879'
        num_better_than_threshold_similsort: '11879'
        rate_of_better_than_threshold_probsort: '0.42158498065798344'
        rate_of_better_than_threshold_similsort: '0.42158498065798344'
        threshold: '0.85'
    topk_probsort: '[0.6431873864715638]'
    topk_similsort: '[0.6431873864715638]'
evaluation_1:
    average_num_of_predictions: '0.9876140114277602'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.25587159313000124'
        mean_fpsd_score_similsort: '0.25587159313000124'
        rate_of_BART_wins_probsort: '0.7182098874968946'
        rate_of_BART_wins_similsort: '0.7182098874968946'
        rate_of_ties_probsort: '0.14345033183092593'
        rate_of_ties_similsort: '0.14345033183092593'
        ties:
            mean_tie_simils_probsort: '0.7253960603763996'
            mean_tie_simils_similsort: '0.7253960603763996'
            num_of_ties_probsort: '4042'
            num_of_ties_simils_equal_to_1_probsort: '1711'
            num_of_ties_simils_equal_to_1_similsort: '1711'
            num_of_ties_similsort: '4042'
            rate_of_ties_simils_equal_to_1_probsort: '0.42330529440870857'
            rate_of_ties_simils_equal_to_1_similsort: '0.42330529440870857'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:32
    formula_stats:
        num_all_correct_formulas: 18223 / 27828
        num_at_least_one_correct_formula: '18223'
        num_correct_formulas_at_best_prob: '18223'
        num_correct_formulas_at_best_simil: '18223'
        rate_of_all_correct_formulas: '0.6548440419721144'
        rate_of_at_least_one_correct_formula: '0.6467331511516485'
        rate_of_correct_formulas_at_best_prob: '0.6467331511516485'
        rate_of_correct_formulas_at_best_simil: '0.6467331511516485'
    hit_at_k_prob: '[(1, 0.41225112680555065)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.164771192157531'
        mean_absolute_mw_difference_best_simil: '6.164771192157531'
        mean_relative_mw_difference_best_prob: 2.23%
        mean_relative_mw_difference_best_simil: 2.23%
        rate_of_exact_mw_prob: '0.6384285055186855'
        rate_of_exact_mw_simil: '0.6384285055186855'
        rate_of_exact_nominal_mw_prob: '0.6799872236221032'
        rate_of_exact_nominal_mw_simil: '0.6799872236221032'
        rate_of_mw_difference_less_than_1_best_prob: '0.7065336976967029'
        rate_of_mw_difference_less_than_1_best_simil: '0.7065336976967029'
    num_datapoints_tested: '28177'
    num_empty_preds: '349'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '11219'
        num_precise_preds_similsort: '11219'
        rate_of_precise_preds_probsort: '0.39816162118039533'
        rate_of_precise_preds_similsort: '0.39816162118039533'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 11616)])
        num_1_hits_as_first_probsort: '11616'
        num_1_hits_as_first_similsort: '11616'
        num_fp_simil_fail_prob: '397'
        num_fp_simil_fail_simil: '397'
        rate_of_1_hits_as_first_probsort: '0.41225112680555065'
        rate_of_1_hits_as_first_similsort: '0.41225112680555065'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '11879'
        num_better_than_threshold_similsort: '11879'
        rate_of_better_than_threshold_probsort: '0.42158498065798344'
        rate_of_better_than_threshold_similsort: '0.42158498065798344'
        threshold: '0.85'
    topk_probsort: '[0.6431873864715638]'
    topk_similsort: '[0.6431873864715638]'
