command: ../predict.py --checkpoint ../checkpoints/finetune_clean/balmy-violet-577_custom_final/checkpoint-147476
  --output-folder predictions --config-file configs/predict_mona_beam10.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
  data_split: all
  dataset_name: MONA_GCMS
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/11/2024 13:21:05
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 06/11/2024 16:11:56
generation_time: 02:50:47
wall_time_utc: 02:50:50
evaluation_0:
    average_num_of_predictions: '9.002791625124626'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:11
    formula_stats:
        num_all_correct_formulas: 7417 / 45149
        num_at_least_one_correct_formula: '2633'
        num_correct_formulas_at_best_prob: '1845'
        num_correct_formulas_at_best_simil: '2160'
        rate_of_all_correct_formulas: '0.16427827858867305'
        rate_of_at_least_one_correct_formula: '0.525024925224327'
        rate_of_correct_formulas_at_best_prob: '0.3678963110667996'
        rate_of_correct_formulas_at_best_simil: '0.4307078763708873'
    hit_at_k_prob: '[(1, 0.19441674975074777), (2, 0.2570289132602193), (3, 0.2827517447657029),
        (4, 0.3000997008973081), (5, 0.3092721834496511), (6, 0.32023928215353936),
        (7, 0.3268195413758724), (8, 0.33100697906281157), (9, 0.33359920239282154),
        (10, 0.3345962113659023)]'
    labels_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '58.00882428788488'
        mean_absolute_mw_difference_best_simil: '58.18660144074252'
        mean_relative_mw_difference_best_prob: 34.35%
        mean_relative_mw_difference_best_simil: 34.38%
        rate_of_exact_mw_prob: '0.364506480558325'
        rate_of_exact_mw_simil: '0.4061814556331007'
        rate_of_exact_nominal_mw_prob: '0.4057826520438684'
        rate_of_exact_nominal_mw_simil: '0.43529411764705883'
        rate_of_mw_difference_less_than_1_best_prob: '0.4271186440677966'
        rate_of_mw_difference_less_than_1_best_simil: '0.45024925224327017'
    num_datapoints_tested: '5015'
    num_empty_preds: '3'
    num_predictions_at_k_counter: '[5015, 4986, 4968, 4929, 4869, 4778, 4614, 4302,
        3843, 2848]'
    precise_preds_stats:
        num_precise_preds_probsort: '935'
        num_precise_preds_similsort: '1648'
        rate_of_precise_preds_probsort: '0.1864406779661017'
        rate_of_precise_preds_similsort: '0.32861415752741774'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 1502), (2, 105), (3, 53), (4, 9), (6,
            1), (5, 7), (7, 1)])
        num_1_hits_as_first_probsort: '975'
        num_1_hits_as_first_similsort: '1678'
        num_fp_simil_fail_prob: '40'
        num_fp_simil_fail_simil: '30'
        rate_of_1_hits_as_first_probsort: '0.19441674975074777'
        rate_of_1_hits_as_first_similsort: '0.3345962113659023'
    start_time_utc: 07/11/2024 14:07:28
    threshold_stats:
        num_better_than_threshold_probsort: '997'
        num_better_than_threshold_similsort: '1698'
        rate_of_better_than_threshold_probsort: '0.1988035892323031'
        rate_of_better_than_threshold_similsort: '0.33858424725822533'
        threshold: '0.85'
    topk_probsort: '[0.3969545639063378, 0.3271635328340514, 0.2951828225498025, 0.27909741066989147,
        0.2717357910155773, 0.26371172234965007, 0.25238537895145957, 0.24575526369697712,
        0.22977899851805272, 0.2117935415965307]'
    topk_similsort: '[0.5259956707823731, 0.3756989695473572, 0.3222073122859695,
        0.28610022402635704, 0.2596075303822561, 0.23474904454958728, 0.21353363226253785,
        0.19089180047142912, 0.166276010245533, 0.14116480810758075]'
