command: predict.py --checkpoint ../checkpoints/finetune_clean/hearty-leaf-572_exp7_custom_rassp/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 31/10/2024 11:35:43
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 31/10/2024 18:46:47
generation_time: 07:11:00
wall_time_utc: 07:11:03
evaluation_0:
    average_num_of_predictions: '0.9843489370763389'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.22288737800762173'
        mean_fpsd_score_similsort: '0.22288737800762173'
        rate_of_BART_wins_probsort: '0.693863789615644'
        rate_of_BART_wins_similsort: '0.693863789615644'
        rate_of_ties_probsort: '0.1420307342868297'
        rate_of_ties_similsort: '0.1420307342868297'
        ties:
            mean_tie_simils_probsort: '0.7274120896520015'
            mean_tie_simils_similsort: '0.7274120896520015'
            num_of_ties_probsort: '4002'
            num_of_ties_simils_equal_to_1_probsort: '1701'
            num_of_ties_simils_equal_to_1_similsort: '1701'
            num_of_ties_similsort: '4002'
            rate_of_ties_simils_equal_to_1_probsort: '0.4250374812593703'
            rate_of_ties_simils_equal_to_1_similsort: '0.4250374812593703'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:32
    formula_stats:
        num_all_correct_formulas: 16713 / 27736
        num_at_least_one_correct_formula: '16713'
        num_correct_formulas_at_best_prob: '16713'
        num_correct_formulas_at_best_simil: '16713'
        rate_of_all_correct_formulas: '0.6025742717046438'
        rate_of_at_least_one_correct_formula: '0.5931433438620152'
        rate_of_correct_formulas_at_best_prob: '0.5931433438620152'
        rate_of_correct_formulas_at_best_simil: '0.5931433438620152'
    hit_at_k_prob: '[(1, 0.3662916563154346)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '7.211317492466793'
        mean_absolute_mw_difference_best_simil: '7.211317492466793'
        mean_relative_mw_difference_best_prob: 2.64%
        mean_relative_mw_difference_best_simil: 2.64%
        rate_of_exact_mw_prob: '0.5851581076764737'
        rate_of_exact_mw_simil: '0.5851581076764737'
        rate_of_exact_nominal_mw_prob: '0.6237001809986868'
        rate_of_exact_nominal_mw_simil: '0.6237001809986868'
        rate_of_mw_difference_less_than_1_best_prob: '0.6513113532313589'
        rate_of_mw_difference_less_than_1_best_simil: '0.6513113532313589'
    num_datapoints_tested: '28177'
    num_empty_preds: '441'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '9806'
        num_precise_preds_similsort: '9806'
        rate_of_precise_preds_probsort: '0.3480143379351954'
        rate_of_precise_preds_similsort: '0.3480143379351954'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 10321)])
        num_1_hits_as_first_probsort: '10321'
        num_1_hits_as_first_similsort: '10321'
        num_fp_simil_fail_prob: '515'
        num_fp_simil_fail_simil: '515'
        rate_of_1_hits_as_first_probsort: '0.3662916563154346'
        rate_of_1_hits_as_first_similsort: '0.3662916563154346'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '10644'
        num_better_than_threshold_similsort: '10644'
        rate_of_better_than_threshold_probsort: '0.3777549064840118'
        rate_of_better_than_threshold_similsort: '0.3777549064840118'
        threshold: '0.85'
    topk_probsort: '[0.6102031713491843]'
    topk_similsort: '[0.6102031713491843]'
