command: ../predict.py --checkpoint ../checkpoints/finetune_clean/balmy-violet-577_custom_final/checkpoint-147476
  --output-folder predictions --config-file configs/predict_swgdrug_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/SWGDRUG_3/SWGDRUG_3_noD.jsonl
  data_split: all
  dataset_name: SWGDRUG
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/11/2024 10:12:29
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 06/11/2024 11:12:33
generation_time: 01:00:01
wall_time_utc: 01:00:04
evaluation_0:
    average_num_of_predictions: '8.955487804878048'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:17
    formula_stats:
        num_all_correct_formulas: 3713 / 14687
        num_at_least_one_correct_formula: '1317'
        num_correct_formulas_at_best_prob: '959'
        num_correct_formulas_at_best_simil: '1122'
        rate_of_all_correct_formulas: '0.25280860625042556'
        rate_of_at_least_one_correct_formula: '0.8030487804878049'
        rate_of_correct_formulas_at_best_prob: '0.5847560975609756'
        rate_of_correct_formulas_at_best_simil: '0.6841463414634147'
    hit_at_k_prob: '[(1, 0.31097560975609756), (2, 0.40182926829268295), (3, 0.45121951219512196),
        (4, 0.48841463414634145), (5, 0.5115853658536585), (6, 0.5317073170731708),
        (7, 0.5457317073170732), (8, 0.552439024390244), (9, 0.5536585365853659)]'
    labels_path: data/extra_libraries/SWGDRUG_3/SWGDRUG_3_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '9.870946346333131'
        mean_absolute_mw_difference_best_simil: '9.15234431089822'
        mean_relative_mw_difference_best_prob: 3.09%
        mean_relative_mw_difference_best_simil: 2.76%
        rate_of_exact_mw_prob: '0.5756097560975609'
        rate_of_exact_mw_simil: '0.6713414634146342'
        rate_of_exact_nominal_mw_prob: '0.6079268292682927'
        rate_of_exact_nominal_mw_simil: '0.6878048780487804'
        rate_of_mw_difference_less_than_1_best_prob: '0.6280487804878049'
        rate_of_mw_difference_less_than_1_best_simil: '0.7036585365853658'
    num_datapoints_tested: '1640'
    num_empty_preds: '1'
    num_predictions_at_k_counter: '[1640, 1635, 1630, 1620, 1607, 1572, 1500, 1409,
        1219, 856]'
    precise_preds_stats:
        num_precise_preds_probsort: '507'
        num_precise_preds_similsort: '907'
        rate_of_precise_preds_probsort: '0.30914634146341463'
        rate_of_precise_preds_similsort: '0.5530487804878049'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 885), (4, 2), (2, 16), (7, 1), (8,
            1), (5, 1), (3, 2)])
        num_1_hits_as_first_probsort: '510'
        num_1_hits_as_first_similsort: '908'
        num_fp_simil_fail_prob: '3'
        num_fp_simil_fail_simil: '1'
        rate_of_1_hits_as_first_probsort: '0.31097560975609756'
        rate_of_1_hits_as_first_similsort: '0.5536585365853659'
    start_time_utc: 06/11/2024 15:52:56
    threshold_stats:
        num_better_than_threshold_probsort: '526'
        num_better_than_threshold_similsort: '931'
        rate_of_better_than_threshold_probsort: '0.3207317073170732'
        rate_of_better_than_threshold_similsort: '0.5676829268292682'
        threshold: '0.85'
    topk_probsort: '[0.6627267307964934, 0.5528030980646449, 0.5158841371611124, 0.49619208541052423,
        0.4821032819309234, 0.4714494059016326, 0.45792976143604697, 0.4378491888503724,
        0.4295462293300725, 0.40623513777814246]'
    topk_similsort: '[0.8062157591329197, 0.6405700809420055, 0.5598893670110687,
        0.5089072329673885, 0.46836361272993987, 0.4332052395450622, 0.399966579251105,
        0.36775140668725714, 0.33816269024278944, 0.2989459709993773]'
