command: spectus/predict.py --checkpoint checkpoints/finetune_clean/balmy-violet-577_exp5_224_148/checkpoint-147476
  --output-folder predictions --config-file configs/predict_mona_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_overlaps_included.jsonl
  data_split: all
  dataset_name: MONA_GCMS_overlaps_only
  query_data: data/extra_libraries/MONA_GCMS/MONA_GCMS_overlaps_only.jsonl
finished_time_utc: 07/11/2024 02:21:14
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
generation_time: 09:48:15
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/11/2024 16:32:43
tokenizer_path: tokenizer/tokenizer_mf10M.model
wall_time_utc: 09:48:30
evaluation_0:
    average_num_of_predictions: '8.233814077441606'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:24
    formula_stats:
        num_all_correct_formulas: 20130 / 105047
        num_at_least_one_correct_formula: '8961'
        num_correct_formulas_at_best_prob: '8041'
        num_correct_formulas_at_best_simil: '8693'
        rate_of_all_correct_formulas: '0.19162850914352622'
        rate_of_at_least_one_correct_formula: '0.7023828186236087'
        rate_of_correct_formulas_at_best_prob: '0.6302712023828186'
        rate_of_correct_formulas_at_best_simil: '0.6813763912839003'
    hit_at_k_prob: '[(1, 0.5620003135287662), (2, 0.6028374353346919), (3, 0.6218059256936824),
        (4, 0.6350525160683492), (5, 0.6438313215237498), (6, 0.6493964571249412),
        (7, 0.6538642420442076), (8, 0.6569211475152845), (9, 0.6588023201128703),
        (10, 0.6589590844960025)]'
    labels_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_overlaps_only.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '41.34688599256946'
        mean_absolute_mw_difference_best_simil: '41.94580647707401'
        mean_relative_mw_difference_best_prob: 27.93%
        mean_relative_mw_difference_best_simil: 28.29%
        rate_of_exact_mw_prob: '0.6289387051261953'
        rate_of_exact_mw_simil: '0.6566076187490202'
        rate_of_exact_nominal_mw_simil: '0.6649945132465904'
        rate_of_mw_difference_less_than_1_best_prob: '0.6601348173694936'
        rate_of_mw_difference_less_than_1_best_simil: '0.6718921461044051'
    num_datapoints_tested: '12758'
    num_empty_preds: '6'
    num_predictions_at_k_counter: '[12758, 12547, 12313, 12023, 11642, 11110, 10327,
        9249, 7671, 5413]'
    precise_preds_stats:
        num_precise_preds_probsort: '7116'
        num_precise_preds_similsort: '8357'
        rate_of_precise_preds_probsort: '0.5577676751841981'
        rate_of_precise_preds_similsort: '0.6550399749176987'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 7653), (2, 557), (3, 152), (4, 24),
            (5, 17), (8, 2), (6, 1), (7, 1)])
        num_1_hits_as_first_probsort: '7170'
        num_1_hits_as_first_similsort: '8407'
        num_fp_simil_fail_prob: '54'
        num_fp_simil_fail_simil: '50'
        rate_of_1_hits_as_first_probsort: '0.5620003135287662'
        rate_of_1_hits_as_first_similsort: '0.6589590844960025'
    start_time_utc: 08/11/2024 10:03:57
    threshold_stats:
        num_better_than_threshold_probsort: '7209'
        num_better_than_threshold_similsort: '8428'
        rate_of_better_than_threshold_probsort: '0.5650572189998432'
        rate_of_better_than_threshold_similsort: '0.6606051105188901'
        threshold: '0.85'
    topk_probsort: '[0.6679309646165678, 0.4129769704000049, 0.381262482580711, 0.3671440689736238,
        0.35189094518335223, 0.3404928327925181, 0.32446887885851206, 0.30771405668056284,
        0.2859337421530148, 0.2570595774227038]'
    topk_similsort: '[0.7460132156671859, 0.5159612234977188, 0.4302815137970269,
        0.37546917024491266, 0.33442978315797683, 0.29936550169128096, 0.26735620512540365,
        0.23674891108420554, 0.20472817284848632, 0.17158273015865688]'
