command: predict.py --checkpoint checkpoints/finetune_clean/youthful-wave-590_exp5_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_swgdrug_beam10.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/SWGDRUG_3/SWGDRUG_3_noD.jsonl
  data_split: all
  dataset_name: SWGDRUG
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 05/01/2025 21:45:07
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 05/01/2025 23:37:37
generation_time: 01:52:27
wall_time_utc: 01:52:30
evaluation_0:
    average_num_of_predictions: '8.539634146341463'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:08
    formula_stats:
        num_all_correct_formulas: 3681 / 14005
        num_at_least_one_correct_formula: '1342'
        num_correct_formulas_at_best_prob: '979'
        num_correct_formulas_at_best_simil: '1170'
        rate_of_all_correct_formulas: '0.2628347018921814'
        rate_of_at_least_one_correct_formula: '0.8182926829268292'
        rate_of_correct_formulas_at_best_prob: '0.5969512195121951'
        rate_of_correct_formulas_at_best_simil: '0.7134146341463414'
    hit_at_k_prob: '[(1, 0.3231707317073171), (2, 0.43658536585365854), (3, 0.5),
        (4, 0.5353658536585366), (5, 0.5548780487804879), (6, 0.5707317073170731),
        (7, 0.5786585365853658), (8, 0.5835365853658536), (9, 0.5865853658536585),
        (10, 0.5878048780487805)]'
    labels_path: data/extra_libraries/SWGDRUG_3/SWGDRUG_3_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '10.612420862845179'
        mean_absolute_mw_difference_best_simil: '8.825193627984255'
        mean_relative_mw_difference_best_prob: 3.34%
        mean_relative_mw_difference_best_simil: 2.69%
        rate_of_exact_mw_prob: '0.5823170731707317'
        rate_of_exact_mw_simil: '0.6926829268292682'
        rate_of_exact_nominal_mw_simil: '0.7079268292682926'
        rate_of_mw_difference_less_than_1_best_prob: '0.6323170731707317'
        rate_of_mw_difference_less_than_1_best_simil: '0.724390243902439'
    num_datapoints_tested: '1640'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[1640, 1636, 1630, 1612, 1572, 1508, 1410, 1251,
        1040, 706]'
    precise_preds_stats:
        num_precise_preds_probsort: '529'
        num_precise_preds_similsort: '960'
        rate_of_precise_preds_probsort: '0.3225609756097561'
        rate_of_precise_preds_similsort: '0.5853658536585366'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 942), (2, 19), (3, 2), (4, 1)])
        num_1_hits_as_first_probsort: '530'
        num_1_hits_as_first_similsort: '964'
        num_fp_simil_fail_prob: '1'
        num_fp_simil_fail_simil: '4'
        rate_of_1_hits_as_first_probsort: '0.3231707317073171'
        rate_of_1_hits_as_first_similsort: '0.5878048780487805'
    start_time_utc: 07/01/2025 13:50:00
    threshold_stats:
        num_better_than_threshold_probsort: '561'
        num_better_than_threshold_similsort: '989'
        rate_of_better_than_threshold_probsort: '0.34207317073170734'
        rate_of_better_than_threshold_similsort: '0.6030487804878049'
        threshold: '0.85'
    topk_probsort: '[0.6799919007148947, 0.5681116856958707, 0.5227462867177879, 0.498035626387554,
        0.48146441471543505, 0.46798127072860074, 0.45366782076726175, 0.44050738358476593,
        0.4228884166929508, 0.40526278770745666]'
    topk_similsort: '[0.8238833859333015, 0.6341515859720384, 0.5576628763908408,
        0.5092798908115457, 0.46770656328902027, 0.4318516959682263, 0.3955254574139444,
        0.36588006224638303, 0.33275388678295376, 0.3006268890974166]'
