command: predict.py --checkpoint ../checkpoints/finetune_clean/royal-violet-583_exp2_lin_10000/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_beam10_exp2_lin_10000.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  do_log_binning: false
  inference_mode: true
  linear_bin_decimals: 4
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 14/12/2024 13:26:43
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 14/12/2024 22:51:38
generation_time: 09:24:50
wall_time_utc: 09:24:54
evaluation_0:
    average_num_of_predictions: '8.776626326436455'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:00
    formula_stats:
        num_all_correct_formulas: 53257 / 247299
        num_at_least_one_correct_formula: '19931'
        num_correct_formulas_at_best_prob: '13677'
        num_correct_formulas_at_best_simil: '16796'
        rate_of_all_correct_formulas: '0.21535469209337685'
        rate_of_at_least_one_correct_formula: '0.7073499662845584'
        rate_of_correct_formulas_at_best_prob: '0.4853958902651098'
        rate_of_correct_formulas_at_best_simil: '0.5960890087660148'
    hit_at_k_prob: '[(1, 0.29655392696170635), (2, 0.3778258863612166), (3, 0.4218334102282003),
        (4, 0.4485218440572098), (5, 0.4675799410867019), (6, 0.4811725875714235),
        (7, 0.4918550590907478), (8, 0.4984561876707953), (9, 0.5028924299960961),
        (10, 0.5048443766192284)]'
    labels_path: data/nist/valid.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '9.85366675829436'
        mean_absolute_mw_difference_best_simil: '10.295836759218606'
        mean_relative_mw_difference_best_prob: 3.71%
        mean_relative_mw_difference_best_simil: 3.79%
        rate_of_exact_mw_prob: '0.479291620825496'
        rate_of_exact_mw_simil: '0.5303971324129609'
        rate_of_exact_nominal_mw_prob: '0.5058380949000958'
        rate_of_exact_nominal_mw_simil: '0.5475032828193207'
        rate_of_mw_difference_less_than_1_best_prob: '0.5324910387905029'
        rate_of_mw_difference_less_than_1_best_simil: '0.5687617560421621'
    num_datapoints_tested: '28177'
    num_empty_preds: '7'
    num_predictions_at_k_counter: '[28177, 28146, 28025, 27784, 27355, 26539, 25167,
        23037, 19505, 13571]'
    precise_preds_stats:
        num_precise_preds_probsort: '7665'
        num_precise_preds_similsort: '14061'
        rate_of_precise_preds_probsort: '0.2720303793874437'
        rate_of_precise_preds_similsort: '0.4990240266884338'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 11345), (2, 1267), (8, 25), (3, 810),
            (6, 93), (5, 178), (4, 409), (7, 62), (9, 24), (10, 12)])
        num_1_hits_as_first_probsort: '8356'
        num_1_hits_as_first_similsort: '14225'
        num_fp_simil_fail_prob: '691'
        num_fp_simil_fail_simil: '164'
        rate_of_1_hits_as_first_probsort: '0.29655392696170635'
        rate_of_1_hits_as_first_similsort: '0.5048443766192284'
    start_time_utc: 08/01/2025 11:06:59
    threshold_stats:
        num_better_than_threshold_probsort: '8735'
        num_better_than_threshold_similsort: '14476'
        rate_of_better_than_threshold_probsort: '0.3100046136920183'
        rate_of_better_than_threshold_similsort: '0.5137523512084324'
        threshold: '0.85'
    topk_probsort: '[0.5646440721737015, 0.4885167899842936, 0.4527772497115606, 0.43360383769928645,
        0.4203347768577458, 0.4059812958703795, 0.393569441182623, 0.37853214789575956,
        0.35870789017914123, 0.33859248077158693]'
    topk_similsort: '[0.7165037446090613, 0.5585656031330504, 0.4920827193279375,
        0.44491706963935745, 0.4048831753385536, 0.37032069753357927, 0.3375377925094238,
        0.30344827615637987, 0.26891113091384583, 0.23498995453092578]'
