command: predict.py --checkpoint checkpoints/finetune_clean/royal-violet-583_exp1_lin_10000/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy_exp1_lin_10000.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  do_log_binning: false
  inference_mode: true
  linear_bin_decimals: 4
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 14/12/2024 13:26:43
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 14/12/2024 17:17:18
generation_time: 03:50:30
wall_time_utc: 03:50:34
evaluation_0:
    average_num_of_predictions: '0.9741278347588459'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:22
    formula_stats:
        num_all_correct_formulas: 13420 / 27448
        num_at_least_one_correct_formula: '13420'
        num_correct_formulas_at_best_prob: '13420'
        num_correct_formulas_at_best_simil: '13420'
        rate_of_all_correct_formulas: '0.48892451180413876'
        rate_of_at_least_one_correct_formula: '0.4762749760442914'
        rate_of_correct_formulas_at_best_prob: '0.4762749760442914'
        rate_of_correct_formulas_at_best_simil: '0.4762749760442914'
    hit_at_k_prob: '[(1, 0.29655392696170635)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '10.245233284124124'
        mean_absolute_mw_difference_best_simil: '10.245233284124124'
        mean_relative_mw_difference_best_prob: 3.89%
        mean_relative_mw_difference_best_simil: 3.89%
        rate_of_exact_mw_prob: '0.47109344500834016'
        rate_of_exact_mw_simil: '0.47109344500834016'
        rate_of_exact_nominal_mw_simil: '0.49590091209142206'
        rate_of_mw_difference_less_than_1_best_prob: '0.52035347978848'
        rate_of_mw_difference_less_than_1_best_simil: '0.52035347978848'
    num_datapoints_tested: '28177'
    num_empty_preds: '729'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '7710'
        num_precise_preds_similsort: '7710'
        rate_of_precise_preds_probsort: '0.2736274266245519'
        rate_of_precise_preds_similsort: '0.2736274266245519'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8356)])
        num_1_hits_as_first_probsort: '8356'
        num_1_hits_as_first_similsort: '8356'
        num_fp_simil_fail_prob: '646'
        num_fp_simil_fail_simil: '646'
        rate_of_1_hits_as_first_probsort: '0.29655392696170635'
        rate_of_1_hits_as_first_similsort: '0.29655392696170635'
    start_time_utc: 14/12/2024 19:46:08
    threshold_stats:
        num_better_than_threshold_probsort: '8698'
        num_better_than_threshold_similsort: '8698'
        rate_of_better_than_threshold_probsort: '0.3086914859637293'
        rate_of_better_than_threshold_similsort: '0.3086914859637293'
        threshold: '0.85'
    topk_probsort: '[0.5521231654496221]'
    topk_similsort: '[0.5521231654496221]'
evaluation_1:
    average_num_of_predictions: '0.9741278347588459'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:22
    formula_stats:
        num_all_correct_formulas: 13420 / 27448
        num_at_least_one_correct_formula: '13420'
        num_correct_formulas_at_best_prob: '13420'
        num_correct_formulas_at_best_simil: '13420'
        rate_of_all_correct_formulas: '0.48892451180413876'
        rate_of_at_least_one_correct_formula: '0.4762749760442914'
        rate_of_correct_formulas_at_best_prob: '0.4762749760442914'
        rate_of_correct_formulas_at_best_simil: '0.4762749760442914'
    hit_at_k_prob: '[(1, 0.29655392696170635)]'
    labels_path: data/nist/valid.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '10.245233284124124'
        mean_absolute_mw_difference_best_simil: '10.245233284124124'
        mean_relative_mw_difference_best_prob: 3.89%
        mean_relative_mw_difference_best_simil: 3.89%
        rate_of_exact_mw_prob: '0.47109344500834016'
        rate_of_exact_mw_simil: '0.47109344500834016'
        rate_of_exact_nominal_mw_simil: '0.49590091209142206'
        rate_of_mw_difference_less_than_1_best_prob: '0.52035347978848'
        rate_of_mw_difference_less_than_1_best_simil: '0.52035347978848'
    num_datapoints_tested: '28177'
    num_empty_preds: '729'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '7710'
        num_precise_preds_similsort: '7710'
        rate_of_precise_preds_probsort: '0.2736274266245519'
        rate_of_precise_preds_similsort: '0.2736274266245519'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 8356)])
        num_1_hits_as_first_probsort: '8356'
        num_1_hits_as_first_similsort: '8356'
        num_fp_simil_fail_prob: '646'
        num_fp_simil_fail_simil: '646'
        rate_of_1_hits_as_first_probsort: '0.29655392696170635'
        rate_of_1_hits_as_first_similsort: '0.29655392696170635'
    start_time_utc: 14/12/2024 19:51:18
    threshold_stats:
        num_better_than_threshold_probsort: '8698'
        num_better_than_threshold_similsort: '8698'
        rate_of_better_than_threshold_probsort: '0.3086914859637293'
        rate_of_better_than_threshold_similsort: '0.3086914859637293'
        threshold: '0.85'
    topk_probsort: '[0.5521231654496221]'
    topk_similsort: '[0.5521231654496221]'
