command: predict.py --checkpoint checkpoints/finetune_clean/youthful-wave-590_exp5_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: GPU-9c7e3cb8-d7e4-720e-d6c3-bd8b1d5256d9
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/01/2025 10:52:35
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 06/01/2025 14:32:52
generation_time: 03:39:43
wall_time_utc: 03:40:16
evaluation_0:
    average_num_of_predictions: '0.9897079178053022'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:27
    formula_stats:
        num_all_correct_formulas: 19325 / 27887
        num_at_least_one_correct_formula: '19325'
        num_correct_formulas_at_best_prob: '19325'
        num_correct_formulas_at_best_simil: '19325'
        rate_of_all_correct_formulas: '0.6929752214293399'
        rate_of_at_least_one_correct_formula: '0.6858430634915001'
        rate_of_correct_formulas_at_best_prob: '0.6858430634915001'
        rate_of_correct_formulas_at_best_simil: '0.6858430634915001'
    hit_at_k_prob: '[(1, 0.4457891187848245)]'
    labels_path: data/nist/valid.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '5.707272108465163'
        mean_absolute_mw_difference_best_simil: '5.707272108465163'
        mean_relative_mw_difference_best_prob: 2.05%
        mean_relative_mw_difference_best_simil: 2.05%
        rate_of_exact_mw_prob: '0.6765446995776697'
        rate_of_exact_mw_simil: '0.6765446995776697'
        rate_of_exact_nominal_mw_prob: '0.7178194981722682'
        rate_of_exact_nominal_mw_simil: '0.7178194981722682'
        rate_of_mw_difference_less_than_1_best_prob: '0.7371260247719772'
        rate_of_mw_difference_less_than_1_best_simil: '0.7371260247719772'
    num_datapoints_tested: '28177'
    num_empty_preds: '290'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '12193'
        num_precise_preds_similsort: '12193'
        rate_of_precise_preds_probsort: '0.43272882137913904'
        rate_of_precise_preds_similsort: '0.43272882137913904'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 12561)])
        num_1_hits_as_first_probsort: '12561'
        num_1_hits_as_first_similsort: '12561'
        num_fp_simil_fail_prob: '368'
        num_fp_simil_fail_simil: '368'
        rate_of_1_hits_as_first_probsort: '0.4457891187848245'
        rate_of_1_hits_as_first_similsort: '0.4457891187848245'
    start_time_utc: 07/01/2025 13:49:59
    threshold_stats:
        num_better_than_threshold_probsort: '12847'
        num_better_than_threshold_similsort: '12847'
        rate_of_better_than_threshold_probsort: '0.4559392412251127'
        rate_of_better_than_threshold_similsort: '0.4559392412251127'
        threshold: '0.85'
    topk_probsort: '[0.6689611172171449]'
    topk_similsort: '[0.6689611172171449]'
