command: src/predict.py --checkpoint ../checkpoints/finetune_clean/balmy-violet-577_exp5_224_148/checkpoint-147476
  --output-folder predictions --config-file configs/predict_mona_greedy.yaml
cuda_visible_devices: '1'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
  data_split: all
  dataset_name: MONA_GCMS
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 06/11/2024 13:21:05
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 06/11/2024 14:05:22
generation_time: 00:44:12
wall_time_utc: 00:44:16
evaluation_0:
    average_num_of_predictions: '0.9808574277168495'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:05
    formula_stats:
        num_all_correct_formulas: 1828 / 4919
        num_at_least_one_correct_formula: '1828'
        num_correct_formulas_at_best_prob: '1828'
        num_correct_formulas_at_best_simil: '1828'
        rate_of_all_correct_formulas: '0.37162024801788984'
        rate_of_at_least_one_correct_formula: '0.364506480558325'
        rate_of_correct_formulas_at_best_prob: '0.364506480558325'
        rate_of_correct_formulas_at_best_simil: '0.364506480558325'
    hit_at_k_prob: '[(1, 0.20099700897308076)]'
    labels_path: data/extra_libraries/MONA_GCMS/MONA_GCMS_noD.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '58.37598574259935'
        mean_absolute_mw_difference_best_simil: '58.37598574259935'
        mean_relative_mw_difference_best_prob: 34.66%
        mean_relative_mw_difference_best_simil: 34.66%
        rate_of_exact_mw_prob: '0.3617148554336989'
        rate_of_exact_mw_simil: '0.3617148554336989'
        rate_of_exact_nominal_mw_prob: '0.4031904287138584'
        rate_of_exact_nominal_mw_simil: '0.4031904287138584'
        rate_of_mw_difference_less_than_1_best_prob: '0.42412761714855435'
        rate_of_mw_difference_less_than_1_best_simil: '0.42412761714855435'
    num_datapoints_tested: '5015'
    num_empty_preds: '96'
    num_predictions_at_k_counter: '[5015]'
    precise_preds_stats:
        num_precise_preds_probsort: '969'
        num_precise_preds_similsort: '969'
        rate_of_precise_preds_probsort: '0.19322033898305085'
        rate_of_precise_preds_similsort: '0.19322033898305085'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 1008)])
        num_1_hits_as_first_probsort: '1008'
        num_1_hits_as_first_similsort: '1008'
        num_fp_simil_fail_prob: '39'
        num_fp_simil_fail_simil: '39'
        rate_of_1_hits_as_first_probsort: '0.20099700897308076'
        rate_of_1_hits_as_first_similsort: '0.20099700897308076'
    start_time_utc: 07/11/2024 14:07:27
    threshold_stats:
        num_better_than_threshold_probsort: '1029'
        num_better_than_threshold_similsort: '1029'
        rate_of_better_than_threshold_probsort: '0.20518444666001995'
        rate_of_better_than_threshold_similsort: '0.20518444666001995'
        threshold: '0.85'
    topk_probsort: '[0.39577585608455335]'
    topk_similsort: '[0.39577585608455335]'
