command: predict.py --checkpoint ../checkpoints/finetune_clean/youthful-wave-590_exp5_9M_448+296/checkpoint-294952
  --output-folder predictions --config-file configs/predict_rcx_inhouse_oo_beam10.yaml
cuda_visible_devices: GPU-83f9775f-f502-4683-141b-c510e5f0c080
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/rcx_inhouse/rcx_inhouse_overlaps_only.jsonl
  data_split: all
  dataset_name: RCX_OO
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 07/01/2025 02:09:56
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 07/01/2025 02:20:00
generation_time: 00:09:59
wall_time_utc: 00:10:03
evaluation_0:
    average_num_of_predictions: '9.537037037037036'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:03
    formula_stats:
        num_all_correct_formulas: 74 / 1030
        num_at_least_one_correct_formula: '46'
        num_correct_formulas_at_best_prob: '35'
        num_correct_formulas_at_best_simil: '41'
        rate_of_all_correct_formulas: '0.07184466019417475'
        rate_of_at_least_one_correct_formula: '0.42592592592592593'
        rate_of_correct_formulas_at_best_prob: '0.32407407407407407'
        rate_of_correct_formulas_at_best_simil: '0.37962962962962965'
    hit_at_k_prob: '[(1, 0.25), (2, 0.2777777777777778), (3, 0.28703703703703703),
        (4, 0.3055555555555556), (5, 0.35185185185185186), (6, 0.3611111111111111)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_overlaps_only.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '44.82488548394444'
        mean_absolute_mw_difference_best_simil: '44.40723418964814'
        mean_relative_mw_difference_best_prob: 13.29%
        mean_relative_mw_difference_best_simil: 13.50%
        rate_of_exact_mw_prob: '0.3148148148148148'
        rate_of_exact_mw_simil: '0.3611111111111111'
        rate_of_exact_nominal_mw_prob: '0.3425925925925926'
        rate_of_exact_nominal_mw_simil: '0.39814814814814814'
        rate_of_mw_difference_less_than_1_best_prob: '0.35185185185185186'
        rate_of_mw_difference_less_than_1_best_simil: '0.39814814814814814'
    num_datapoints_tested: '108'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[108, 108, 108, 108, 108, 108, 106, 105, 93, 78]'
    precise_preds_stats:
        num_precise_preds_probsort: '27'
        num_precise_preds_similsort: '39'
        rate_of_precise_preds_probsort: '0.25'
        rate_of_precise_preds_similsort: '0.3611111111111111'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 38), (3, 1)])
        num_1_hits_as_first_probsort: '27'
        num_1_hits_as_first_similsort: '39'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.25'
        rate_of_1_hits_as_first_similsort: '0.3611111111111111'
    start_time_utc: 07/01/2025 13:49:59
    threshold_stats:
        num_better_than_threshold_probsort: '27'
        num_better_than_threshold_similsort: '39'
        rate_of_better_than_threshold_probsort: '0.25'
        rate_of_better_than_threshold_similsort: '0.3611111111111111'
        threshold: '0.85'
    topk_probsort: '[0.47349063530478297, 0.3565321162958914, 0.34968987407621716,
        0.3457588075793255, 0.3564302776315893, 0.34040252862110243, 0.3315733576635867,
        0.30199806564775417, 0.3144829428283215, 0.2662863743594316]'
    topk_similsort: '[0.6124360770933607, 0.44803267639950406, 0.39606245900421677,
        0.3594783205799827, 0.32631006545456726, 0.30513839498022816, 0.2865384803650049,
        0.25593697495160556, 0.21857355633109518, 0.19209507985518312]'
