command: predict.py --checkpoint ../checkpoints/finetune_clean/valiant-galaxy-574_exp3_custom_rassp_neims_nist/checkpoint-73738
  --output-folder predictions --config-file configs/predict_nist_valid_greedy.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/valid.jsonl
  data_split: valid
  dataset_name: NIST
general:
  additional_naming_info: greedy
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 1
  num_return_sequences: 1
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 31/10/2024 11:35:43
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 31/10/2024 18:47:25
generation_time: 07:11:38
wall_time_utc: 07:11:41
evaluation_0:
    average_num_of_predictions: '0.9852716754800014'
    db_search:
        mean_db_score: '0.3873157933415626'
        mean_fpsd_score_probsort: '0.23759482540807464'
        mean_fpsd_score_similsort: '0.23759482540807464'
        rate_of_spectus_wins_probsort: '0.7037299925471129'
        rate_of_spectus_wins_similsort: '0.7037299925471129'
        rate_of_ties_probsort: '0.141533875146396'
        rate_of_ties_similsort: '0.141533875146396'
        ties:
            mean_tie_simils_probsort: '0.7287899334587434'
            mean_tie_simils_similsort: '0.7287899334587434'
            num_of_ties_probsort: '3988'
            num_of_ties_simils_equal_to_1_probsort: '1696'
            num_of_ties_simils_equal_to_1_similsort: '1696'
            num_of_ties_similsort: '3988'
            rate_of_ties_simils_equal_to_1_probsort: '0.42527582748244735'
            rate_of_ties_simils_equal_to_1_similsort: '0.42527582748244735'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:32
    formula_stats:
        num_all_correct_formulas: 17796 / 27762
        num_at_least_one_correct_formula: '17796'
        num_correct_formulas_at_best_prob: '17796'
        num_correct_formulas_at_best_simil: '17796'
        rate_of_all_correct_formulas: '0.6410200994164685'
        rate_of_at_least_one_correct_formula: '0.631578947368421'
        rate_of_correct_formulas_at_best_prob: '0.631578947368421'
        rate_of_correct_formulas_at_best_simil: '0.631578947368421'
    hit_at_k_prob: '[(1, 0.390353834687866)]'
    labels_path: data/nist/valid_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.562802124844123'
        mean_absolute_mw_difference_best_simil: '6.562802124844123'
        mean_relative_mw_difference_best_prob: 2.35%
        mean_relative_mw_difference_best_simil: 2.35%
        rate_of_exact_mw_prob: '0.6222450935159882'
        rate_of_exact_mw_simil: '0.6222450935159882'
        rate_of_exact_nominal_mw_prob: '0.6673173155410441'
        rate_of_exact_nominal_mw_simil: '0.6673173155410441'
        rate_of_mw_difference_less_than_1_best_prob: '0.6951414274053306'
        rate_of_mw_difference_less_than_1_best_simil: '0.6951414274053306'
    num_datapoints_tested: '28177'
    num_empty_preds: '415'
    num_predictions_at_k_counter: '[28177]'
    precise_preds_stats:
        num_precise_preds_probsort: '10597'
        num_precise_preds_similsort: '10597'
        rate_of_precise_preds_probsort: '0.3760868793696987'
        rate_of_precise_preds_similsort: '0.3760868793696987'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 10999)])
        num_1_hits_as_first_probsort: '10999'
        num_1_hits_as_first_similsort: '10999'
        num_fp_simil_fail_prob: '402'
        num_fp_simil_fail_simil: '402'
        rate_of_1_hits_as_first_probsort: '0.390353834687866'
        rate_of_1_hits_as_first_similsort: '0.390353834687866'
    start_time_utc: 05/11/2024 10:26:28
    threshold_stats:
        num_better_than_threshold_probsort: '11286'
        num_better_than_threshold_similsort: '11286'
        rate_of_better_than_threshold_probsort: '0.4005394470667566'
        rate_of_better_than_threshold_similsort: '0.4005394470667566'
        threshold: '0.85'
    topk_probsort: '[0.6249106187496373]'
    topk_similsort: '[0.6249106187496373]'
