apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spectus
  annotations:
    kuberentes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
    - hosts:
        - spectus-demo.dyn.cloud.e-infra.cz
      secretName: spectus-tls
  rules:
    - host: spectus-demo.dyn.cloud.e-infra.cz
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: spectus
                port:
                  number: 80
