apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spectus-checkpoints
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust the storage size as needed
  storageClassName: nfs-csi
