command: ../predict.py --checkpoint ../checkpoints/finetune_clean/balmy-violet-577_custom_final/checkpoint-147476
  --output-folder predictions --config-file configs/predict_rcx_inhouse_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/rcx_inhouse/rcx_inhouse_overlaps_only.jsonl
  data_split: all
  dataset_name: RCX_NO
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 15/11/2024 13:06:49
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 15/11/2024 13:11:47
generation_time: 00:04:53
wall_time_utc: 00:04:57
evaluation_0:
    average_num_of_predictions: '9.38888888888889'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:04
    formula_stats:
        num_all_correct_formulas: 72 / 1014
        num_at_least_one_correct_formula: '45'
        num_correct_formulas_at_best_prob: '27'
        num_correct_formulas_at_best_simil: '41'
        rate_of_all_correct_formulas: '0.07100591715976332'
        rate_of_at_least_one_correct_formula: '0.4166666666666667'
        rate_of_correct_formulas_at_best_prob: '0.25'
        rate_of_correct_formulas_at_best_simil: '0.37962962962962965'
    hit_at_k_prob: '[(1, 0.21296296296296297), (2, 0.24074074074074073), (3, 0.28703703703703703),
        (4, 0.3148148148148148), (5, 0.32407407407407407), (6, 0.35185185185185186),
        (7, 0.37037037037037035)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_overlaps_only.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '41.65906170938888'
        mean_absolute_mw_difference_best_simil: '39.945742258370366'
        mean_relative_mw_difference_best_prob: 12.94%
        mean_relative_mw_difference_best_simil: 12.23%
        rate_of_exact_mw_prob: '0.25'
        rate_of_exact_mw_simil: '0.39814814814814814'
        rate_of_exact_nominal_mw_prob: '0.26851851851851855'
        rate_of_exact_nominal_mw_simil: '0.4166666666666667'
        rate_of_mw_difference_less_than_1_best_prob: '0.26851851851851855'
        rate_of_mw_difference_less_than_1_best_simil: '0.4166666666666667'
    num_datapoints_tested: '108'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[108, 108, 108, 108, 108, 108, 107, 104, 91, 64]'
    precise_preds_stats:
        num_precise_preds_probsort: '23'
        num_precise_preds_similsort: '40'
        rate_of_precise_preds_probsort: '0.21296296296296297'
        rate_of_precise_preds_similsort: '0.37037037037037035'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 38), (2, 2)])
        num_1_hits_as_first_probsort: '23'
        num_1_hits_as_first_similsort: '40'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.21296296296296297'
        rate_of_1_hits_as_first_similsort: '0.37037037037037035'
    start_time_utc: 15/11/2024 15:17:18
    threshold_stats:
        num_better_than_threshold_probsort: '23'
        num_better_than_threshold_similsort: '40'
        rate_of_better_than_threshold_probsort: '0.21296296296296297'
        rate_of_better_than_threshold_similsort: '0.37037037037037035'
        threshold: '0.85'
    topk_probsort: '[0.4602729430449393, 0.36192324643891177, 0.3717358804082743,
        0.3624116432277484, 0.33926138732875355, 0.34100958058402603, 0.3395529575493996,
        0.3138454937894925, 0.2821230993208572, 0.2733895529264745]'
    topk_similsort: '[0.6131446036751006, 0.46755479402260247, 0.40186981339258226,
        0.36644106415088956, 0.3289711921264132, 0.2971796754804402, 0.27386683920027466,
        0.24747056492825587, 0.21264977225036563, 0.18730302405583735]'
evaluation_1:
    average_num_of_predictions: '9.38888888888889'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:04
    formula_stats:
        num_all_correct_formulas: 72 / 1014
        num_at_least_one_correct_formula: '45'
        num_correct_formulas_at_best_prob: '27'
        num_correct_formulas_at_best_simil: '41'
        rate_of_all_correct_formulas: '0.07100591715976332'
        rate_of_at_least_one_correct_formula: '0.4166666666666667'
        rate_of_correct_formulas_at_best_prob: '0.25'
        rate_of_correct_formulas_at_best_simil: '0.37962962962962965'
    hit_at_k_prob: '[(1, 0.21296296296296297), (2, 0.24074074074074073), (3, 0.28703703703703703),
        (4, 0.3148148148148148), (5, 0.32407407407407407), (6, 0.35185185185185186),
        (7, 0.37037037037037035)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_overlaps_only.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '41.65906170938888'
        mean_absolute_mw_difference_best_simil: '39.945742258370366'
        mean_relative_mw_difference_best_prob: 12.94%
        mean_relative_mw_difference_best_simil: 12.23%
        rate_of_exact_mw_prob: '0.25'
        rate_of_exact_mw_simil: '0.39814814814814814'
        rate_of_exact_nominal_mw_prob: '0.26851851851851855'
        rate_of_exact_nominal_mw_simil: '0.4166666666666667'
        rate_of_mw_difference_less_than_1_best_prob: '0.26851851851851855'
        rate_of_mw_difference_less_than_1_best_simil: '0.4166666666666667'
    num_datapoints_tested: '108'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[108, 108, 108, 108, 108, 108, 107, 104, 91, 64]'
    precise_preds_stats:
        num_precise_preds_probsort: '23'
        num_precise_preds_similsort: '40'
        rate_of_precise_preds_probsort: '0.21296296296296297'
        rate_of_precise_preds_similsort: '0.37037037037037035'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 38), (2, 2)])
        num_1_hits_as_first_probsort: '23'
        num_1_hits_as_first_similsort: '40'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.21296296296296297'
        rate_of_1_hits_as_first_similsort: '0.37037037037037035'
    start_time_utc: 15/11/2024 15:21:25
    threshold_stats:
        num_better_than_threshold_probsort: '23'
        num_better_than_threshold_similsort: '40'
        rate_of_better_than_threshold_probsort: '0.21296296296296297'
        rate_of_better_than_threshold_similsort: '0.37037037037037035'
        threshold: '0.85'
    topk_probsort: '[0.4602729430449393, 0.36192324643891177, 0.3717358804082743,
        0.3624116432277484, 0.33926138732875355, 0.34100958058402603, 0.3395529575493996,
        0.3138454937894925, 0.2821230993208572, 0.2733895529264745]'
    topk_similsort: '[0.6131446036751006, 0.46755479402260247, 0.40186981339258226,
        0.36644106415088956, 0.3289711921264132, 0.2971796754804402, 0.27386683920027466,
        0.24747056492825587, 0.21264977225036563, 0.18730302405583735]'
evaluation_2:
    average_num_of_predictions: '9.38888888888889'
    eval_config:
        do_db_search: false
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:00:02
    formula_stats:
        num_all_correct_formulas: 72 / 1014
        num_at_least_one_correct_formula: '45'
        num_correct_formulas_at_best_prob: '27'
        num_correct_formulas_at_best_simil: '41'
        rate_of_all_correct_formulas: '0.07100591715976332'
        rate_of_at_least_one_correct_formula: '0.4166666666666667'
        rate_of_correct_formulas_at_best_prob: '0.25'
        rate_of_correct_formulas_at_best_simil: '0.37962962962962965'
    hit_at_k_prob: '[(1, 0.21296296296296297), (2, 0.24074074074074073), (3, 0.28703703703703703),
        (4, 0.3148148148148148), (5, 0.32407407407407407), (6, 0.35185185185185186),
        (7, 0.37037037037037035)]'
    labels_path: data/rcx_inhouse/rcx_inhouse_overlaps_only.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '41.65906170938888'
        mean_absolute_mw_difference_best_simil: '39.945742258370366'
        mean_relative_mw_difference_best_prob: 12.94%
        mean_relative_mw_difference_best_simil: 12.23%
        rate_of_exact_mw_prob: '0.25'
        rate_of_exact_mw_simil: '0.39814814814814814'
        rate_of_exact_nominal_mw_prob: '0.26851851851851855'
        rate_of_exact_nominal_mw_simil: '0.4166666666666667'
        rate_of_mw_difference_less_than_1_best_prob: '0.26851851851851855'
        rate_of_mw_difference_less_than_1_best_simil: '0.4166666666666667'
    num_datapoints_tested: '108'
    num_empty_preds: '0'
    num_predictions_at_k_counter: '[108, 108, 108, 108, 108, 108, 107, 104, 91, 64]'
    precise_preds_stats:
        num_precise_preds_probsort: '23'
        num_precise_preds_similsort: '40'
        rate_of_precise_preds_probsort: '0.21296296296296297'
        rate_of_precise_preds_similsort: '0.37037037037037035'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 38), (2, 2)])
        num_1_hits_as_first_probsort: '23'
        num_1_hits_as_first_similsort: '40'
        num_fp_simil_fail_prob: '0'
        num_fp_simil_fail_simil: '0'
        rate_of_1_hits_as_first_probsort: '0.21296296296296297'
        rate_of_1_hits_as_first_similsort: '0.37037037037037035'
    start_time_utc: 15/11/2024 15:31:06
    threshold_stats:
        num_better_than_threshold_probsort: '23'
        num_better_than_threshold_similsort: '40'
        rate_of_better_than_threshold_probsort: '0.21296296296296297'
        rate_of_better_than_threshold_similsort: '0.37037037037037035'
        threshold: '0.85'
    topk_probsort: '[0.4602729430449393, 0.36192324643891177, 0.3717358804082743,
        0.3624116432277484, 0.33926138732875355, 0.34100958058402603, 0.3395529575493996,
        0.3138454937894925, 0.2821230993208572, 0.2733895529264745]'
    topk_similsort: '[0.6131446036751006, 0.46755479402260247, 0.40186981339258226,
        0.36644106415088956, 0.3289711921264132, 0.2971796754804402, 0.27386683920027466,
        0.24747056492825587, 0.21264977225036563, 0.18730302405583735]'
