command: predict.py --checkpoint ../checkpoints/finetune_clean/balmy-violet-577_custom_final/checkpoint-147476
  --output-folder predictions --config-file configs/predict_nist_test_beam10.yaml
cuda_visible_devices: '2'
dataloader:
  batch_size: 1
  num_workers: 1
dataset:
  data_path: data/nist/test.jsonl
  data_split: test
  dataset_name: NIST
general:
  additional_naming_info: beam10
  device: cuda
generation_args:
  do_sample: false
  length_penalty: 1.0
  max_length: 200
  num_beams: 10
  num_return_sequences: 10
  penalty_alpha: null
  temperature: null
  top_k: null
  top_p: null
preprocess_args:
  inference_mode: true
  log_base: 1.28
  log_shift: 29
  max_cumsum: null
  max_mol_repr_len: 100
  max_mz: 500
  max_num_peaks: 300
  mol_repr: smiles
  restrict_intensities: false
  source_token: <nist>
start_loading_time: 04/11/2024 12:35:58
tokenizer_path: tokenizer/tokenizer_mf10M.model
finished_time_utc: 05/11/2024 00:28:57
generation_time: '11:52:53'
wall_time_utc: '11:52:59'
evaluation_0:
    average_num_of_predictions: '8.390844447589062'
    db_search:
        mean_db_score: '0.3879342743657602'
        mean_fpsd_score_probsort: '0.2572588679812755'
        mean_fpsd_score_similsort: '0.40282488406648853'
        rate_of_BART_wins_probsort: '0.7220433721300457'
        rate_of_BART_wins_similsort: '0.8670888314996286'
        rate_of_ties_probsort: '0.09198004740510135'
        rate_of_ties_similsort: '0.09198004740510135'
        ties:
            mean_tie_simils_probsort: '0.8464809677893275'
            mean_tie_simils_similsort: '0.8773866989004854'
            num_of_ties_probsort: '2600'
            num_of_ties_simils_equal_to_1_probsort: '1777'
            num_of_ties_simils_equal_to_1_similsort: '1901'
            num_of_ties_similsort: '2600'
            rate_of_ties_simils_equal_to_1_probsort: '0.6834615384615385'
            rate_of_ties_simils_equal_to_1_similsort: '0.7311538461538462'
    eval_config:
        do_db_search: true
        filtering_args:
            max_mol_repr_len: 100
            max_mz: 500
            max_num_peaks: 300
            mol_repr: smiles
        fingerprint_type: morgan
        fp_simil_function: tanimoto
        on_the_fly: true
        save_best_predictions: true
        threshold: 0.85
    eval_time: 00:01:01
    formula_stats:
        num_all_correct_formulas: 70102 / 237184
        num_at_least_one_correct_formula: '23649'
        num_correct_formulas_at_best_prob: '18116'
        num_correct_formulas_at_best_simil: '20948'
        rate_of_all_correct_formulas: '0.295559565569347'
        rate_of_at_least_one_correct_formula: '0.8366292850320162'
        rate_of_correct_formulas_at_best_prob: '0.6408886687656985'
        rate_of_correct_formulas_at_best_simil: '0.7410761665546397'
    hit_at_k_prob: '[(1, 0.3957618424311034), (2, 0.49021827572788057), (3, 0.5381186542611526),
        (4, 0.5672338769589981), (5, 0.5880708953903846), (6, 0.6021862949729366),
        (7, 0.6115965613613047), (8, 0.6181412955035908), (9, 0.6216082357519369),
        (10, 0.6227756748151555)]'
    labels_path: data/nist/test_with_db_index.jsonl
    molecular_weight_stats:
        mean_absolute_mw_difference_best_prob: '6.163344197689456'
        mean_absolute_mw_difference_best_simil: '6.727264533728446'
        mean_relative_mw_difference_best_prob: 2.22%
        mean_relative_mw_difference_best_simil: 2.36%
        rate_of_exact_mw_prob: '0.6305586019032794'
        rate_of_exact_mw_simil: '0.6590370396575512'
        rate_of_exact_nominal_mw_prob: '0.6723387695899813'
        rate_of_exact_nominal_mw_simil: '0.68270421339371'
        rate_of_mw_difference_less_than_1_best_prob: '0.7018785155835426'
        rate_of_mw_difference_less_than_1_best_simil: '0.7032582162946192'
    num_datapoints_tested: '28267'
    num_empty_preds: '3'
    num_predictions_at_k_counter: '[28267, 28172, 27932, 27492, 26776, 25545, 23710,
        21021, 17164, 11108]'
    precise_preds_stats:
        num_precise_preds_probsort: '10620'
        num_precise_preds_similsort: '17489'
        rate_of_precise_preds_probsort: '0.3757031167085294'
        rate_of_precise_preds_similsort: '0.6187073265645452'
    simil_1_hits:
        counter_multiple_hits: dict_items([(1, 14587), (2, 1365), (3, 1084), (4, 321),
            (7, 29), (6, 64), (5, 141), (8, 10), (9, 3)])
        num_1_hits_as_first_probsort: '11187'
        num_1_hits_as_first_similsort: '17604'
        num_fp_simil_fail_prob: '567'
        num_fp_simil_fail_simil: '115'
        rate_of_1_hits_as_first_probsort: '0.3957618424311034'
        rate_of_1_hits_as_first_similsort: '0.6227756748151555'
    start_time_utc: 05/11/2024 09:46:11
    threshold_stats:
        num_better_than_threshold_probsort: '11505'
        num_better_than_threshold_similsort: '17777'
        rate_of_better_than_threshold_probsort: '0.4070117097675735'
        rate_of_better_than_threshold_similsort: '0.6288958856617257'
        threshold: '0.85'
    topk_probsort: '[0.6451931423470357, 0.5315153655377917, 0.4883103328811756, 0.45918267503209576,
        0.44307826224089336, 0.4250568369239263, 0.4067382173554603, 0.38719537691398564,
        0.36250831734785904, 0.33934156370077617]'
    topk_similsort: '[0.7907591584322488, 0.5948279352923634, 0.5196112466092997,
        0.46625599069260404, 0.42335664784951826, 0.38535025620477564, 0.349449305328792,
        0.313474372330255, 0.27806759729694425, 0.24324932420453954]'
